### ISSUE TITLE
"InterfaceError: connection already closed" thrown when storing task results

### ISSUE THREAD

**Issue by dfujiwara** [celery/django-celery#121]
I am getting a following exception using these combination of packages.

Django==1.2.1
django-celery==2.5.1
celery==2.5.1
psycopg2==2.4.4

Traceback (most recent call last):
  File "/home/nextdoor/src/nextdoor.com-20120323-231124-51670d3e937a315ee1eeff1aca35191189cefd31/ve-32/lib/python2.6/site-packages/celery/execute/trace.py", line 158, in trace_task
    R = I.handle_error_state(task, eager=eager)
  File "/home/nextdoor/src/nextdoor.com-20120323-231124-51670d3e937a315ee1eeff1aca35191189cefd31/ve-32/lib/python2.6/site-packages/celery/execute/trace.py", line 68, in handle_error_state
    }[self.state](task, store_errors=store_errors)
  File "/home/nextdoor/src/nextdoor.com-20120323-231124-51670d3e937a315ee1eeff1aca35191189cefd31/ve-32/lib/python2.6/site-packages/celery/execute/trace.py", line 80, in handle_retry
    task.backend.mark_as_retry(req.id, orig_exc, self.strtb)
  File "/home/nextdoor/src/nextdoor.com-20120323-231124-51670d3e937a315ee1eeff1aca35191189cefd31/ve-32/lib/python2.6/site-packages/celery/backends/base.py", line 102, in mark_as_retry
    traceback=traceback)
  File "/home/nextdoor/src/nextdoor.com-20120323-231124-51670d3e937a315ee1eeff1aca35191189cefd31/ve-32/lib/python2.6/site-packages/celery/backends/base.py", line 229, in store_result
    return self._store_result(task_id, result, status, traceback, **kwargs)
  File "/home/nextdoor/src/nextdoor.com-20120323-231124-51670d3e937a315ee1eeff1aca35191189cefd31/ve-32/lib/python2.6/site-packages/djcelery/backends/database.py", line 27, in _store_result
    traceback=traceback)
  File "/home/nextdoor/src/nextdoor.com-20120323-231124-51670d3e937a315ee1eeff1aca35191189cefd31/ve-32/lib/python2.6/site-packages/djcelery/managers.py", line 50, in _inner
    transaction.rollback_unless_managed()
  File "/home/nextdoor/src/nextdoor.com-20120323-231124-51670d3e937a315ee1eeff1aca35191189cefd31/ve-32/lib/python2.6/site-packages/django/db/transaction.py", line 188, in rollback_unless_managed
    connection._rollback()
  File "/home/nextdoor/src/nextdoor.com-20120323-231124-51670d3e937a315ee1eeff1aca35191189cefd31/ve-32/lib/python2.6/site-packages/django/db/backends/__init__.py", line 36, in _rollback
    return self.connection.rollback()
InterfaceError: connection already closed

I am assuming that the transaction_retry decorator defined in djcelery/managers.py surrounding store_result of TaskManager is catching an InterfaceError exception when attempting to commit the change to db, but in the process of handling the exception in the decoration, it unfortunately encounters the same exception when attempting to rollback the transaction. 

Has anyone seen this before?

**Comment by rychlis** [comment]
We just hit this issue in a production environment
```
Django==1.11.11
celery==4.1.0
psycopg2==2.7.3.1 (django.db.backends.postgresql_psycopg2 backend)
```
There is nothing in postgresql logs. I guess one of the threads (we use perfork with 4 concurrent tasks) lost connection and afterwards every query ended with `connection already closed`. We should implement a liveness check that would kill workers without postgresql connection to workaround this, however the reasoning behind closing this issue doesn't make sense to me:

> Note that django-celery does close the Django database connections after fork, it will not do anything about manually created database connection created outside of the django.db framework.

What do you mean by connection creating outside of the django.db framework? Noone here is mentioning anything like that, we are using pretty standard tools - psycopg2, Celery and Django. How is that connection created outside of django.db framework?

I guess in 2013 psycopg2 was not part of django.db, now it actually is, maybe it's time to re-open? @ask

**Comment by latusaki** [comment]
I am getting this issue as well, it always happens with the following:
* celery task starts, accesses database
* A 30-minute API polling loop runs
* task attempts to update DB model
*   ```File "/usr/local/lib/python3.6/site-packages/django/db/backends/postgresql/base.py", line 238, in _set_autocommit
    self.connection.autocommit = autocommit
psycopg2.InterfaceError: connection already closed
```

**Comment by thenewguy** [comment]
Happened across this on stackoverflow.  Surprised this is still a problem.  This might help someone

```
class FaultTolerantTask(celery.Task):
    """ Implements after return hook to close the invalid connection.
    This way, django is forced to serve a new connection for the next
    task.
    """
    abstract = True

    def after_return(self, *args, **kwargs):
        connection.close()
```

Copied from https://stackoverflow.com/a/36580629/319862

**Comment by goldensectionlv** [comment]
i had the same problem. It appeared periodically. My base in postgresql had 'ssl required' and I did not write this moment in self.conn = psycopg2.connect () . Now i fixed it, seems to work.. 


DATABASE_URL = os.environ['DATABASE_URL']

conn = psycopg2.connect(DATABASE_URL, s**slmode='require'**)

**Comment by dd84ai** [comment]
if someone would be searching why they have Interface Error: connection already closed due to Django ORM usage in celery task with Celery worker fixture, then there is issue there about it https://github.com/celery/celery/issues/4511

**Comment by michaelschem** [comment]
Is this issue only created when using Prefork? If I'm only using concurrency of 1, can I avoid this issue by not using Prefork?
