### ISSUE TITLE
celerybeat raises exception if there is a periodic task with no interval/crontab selected

### ISSUE THREAD

**Issue by i-trofimtschuk** [celery/django-celery#126]
If one of interval/crontab is required, the admin form should raise validation errors i think.

Here is a log:

```
[2012-04-10 01:47:26,938: WARNING/MainProcess] celerybeat v2.5.1 is starting.
[2012-04-10 01:47:27,072: WARNING/MainProcess] __    -    ... __   -        _
Configuration ->
    . broker -> redis://localhost:6379/0
    . loader -> djcelery.loaders.DjangoLoader
    . scheduler -> djcelery.schedulers.DatabaseScheduler

    . logfile -> /var/log/celerybeat_live.log@INFO
    . maxinterval -> 5.00 minutes (300s)
[2012-04-10 01:47:27,072: INFO/MainProcess] Celerybeat: Starting...
[2012-04-10 01:47:27,146: CRITICAL/MainProcess] celerybeat raised exception <type 'exceptions.AttributeError'>: AttributeError("'NoneType' object has no attribute 'is_due'",)
Traceback (most recent call last):
  File "/var/www/yf_live/virtualenv/lib/python2.6/site-packages/celery/apps/beat.py", line 89, in start_scheduler
    beat.start()
  File "/var/www/yf_live/virtualenv/lib/python2.6/site-packages/celery/beat.py", line 406, in start
    interval = self.scheduler.tick()
  File "/var/www/yf_live/virtualenv/lib/python2.6/site-packages/celery/beat.py", line 197, in tick
    next_time_to_run = self.maybe_due(entry, self.publisher)
  File "/var/www/yf_live/virtualenv/lib/python2.6/site-packages/celery/beat.py", line 173, in maybe_due
    is_due, next_time_to_run = entry.is_due()
  File "/var/www/yf_live/virtualenv/lib/python2.6/site-packages/djcelery/schedulers.py", line 54, in is_due
    return self.schedule.is_due(self.last_run_at)
AttributeError: 'NoneType' object has no attribute 'is_due'
Traceback (most recent call last):
  File "/var/www/yf_live/virtualenv/lib/python2.6/site-packages/celery/apps/beat.py", line 89, in start_scheduler
    beat.start()
  File "/var/www/yf_live/virtualenv/lib/python2.6/site-packages/celery/beat.py", line 406, in start
    interval = self.scheduler.tick()
  File "/var/www/yf_live/virtualenv/lib/python2.6/site-packages/celery/beat.py", line 197, in tick
    next_time_to_run = self.maybe_due(entry, self.publisher)
  File "/var/www/yf_live/virtualenv/lib/python2.6/site-packages/celery/beat.py", line 173, in maybe_due
    is_due, next_time_to_run = entry.is_due()
  File "/var/www/yf_live/virtualenv/lib/python2.6/site-packages/djcelery/schedulers.py", line 54, in is_due
    return self.schedule.is_due(self.last_run_at)
AttributeError: 'NoneType' object has no attribute 'is_due'
[2012-04-10 01:47:27,146: INFO/MainProcess] process shutting down
```

**Comment by garromark** [comment]
If anyone encounters this, for me it was a trailing comma/typo that misconfigured a scheduled task without breaking anything else.

**Comment by georgepsarakis** [comment]
@garromark thanks for sharing a possible troubleshooting here.
