### ISSUE TITLE
DatabaseError: column celery_taskmeta.hidden does not exist

### ISSUE THREAD

**Issue by leeschmidt4** [celery/django-celery#206]
I am using celery == 3.0.9 and django-celery == 3.0.9 and using "django://" as the broker url. I am using postgresql as my django backend. I am running celery as a daemon.

Contents of /etc/default/celeryd:

CELERYD_NODES="w1"
CELERYD_CHDIR="/path/to/my/project"
CELERYD_MULTI="$CELERYD_CHDIR/manage.py celeryd_multi"
CELERYCTL="$CELERYD_CHDIR/manage.py celeryctl"
CELERYD_OPTS="--time-limit=1800 --concurrency=5"
CELERY_CONFIG_MODULE="celeryconfig"
CELERYD_LOG_FILE="/var/log/celery/%n.log"
CELERYD_PID_FILE="/var/run/celery/%n.pid"
CELERYD_USER="ec2-user"
CELERYD_GROUP="ec2-user"

And in my django settings:

BROKER_URL = 'django://'

Here is the error I get:

[2012-11-02 04:00:05,359: CRITICAL/MainProcess] Task celery.backend_cleanup[5d80ce0a-89da-42dd-b89c-f68b08bb50a1]    INTERNAL ERROR: DatabaseError('column celery_taskmeta.hidden does not exist\nLINE 1: ...meta"."date_done", "celery_taskmeta"."traceback", "celery_ta...\n                                                             ^\n',)
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/celery/task/trace.py", line 235, in trace_task
    R = I.handle_error_state(task, eager=eager)
  File "/usr/lib/python2.6/site-packages/celery/task/trace.py", line 104, in handle_error_state
    }[self.state](task, store_errors=store_errors)
  File "/usr/lib/python2.6/site-packages/celery/task/trace.py", line 130, in handle_failure
    task.backend.mark_as_failure(req.id, exc, einfo.traceback)
  File "/usr/lib/python2.6/site-packages/celery/backends/base.py", line 113, in mark_as_failure
    traceback=traceback)
  File "/usr/lib/python2.6/site-packages/celery/backends/base.py", line 257, in store_result
    self._store_result(task_id, result, status, traceback, **kwargs)
  File "/usr/lib/python2.6/site-packages/djcelery/backends/database.py", line 27, in _store_result
    traceback=traceback, children=self.current_task_children())
  File "/usr/lib/python2.6/site-packages/djcelery/managers.py", line 41, in _inner
    return fun(_args, *_kwargs)
  File "/usr/lib/python2.6/site-packages/djcelery/managers.py", line 174, in store_result
    "meta": {"children": children}})
  File "/usr/lib/python2.6/site-packages/djcelery/managers.py", line 83, in update_or_create
    return self.get_query_set().update_or_create(**kwargs)
  File "/usr/lib/python2.6/site-packages/djcelery/managers.py", line 67, in update_or_create
    obj, created = self.get_or_create(**kwargs)
  File "/usr/lib/python2.6/site-packages/django/db/models/query.py", line 378, in get_or_create
    return self.get(**lookup), False
  File "/usr/lib/python2.6/site-packages/django/db/models/query.py", line 344, in get
    num = len(clone)
  File "/usr/lib/python2.6/site-packages/django/db/models/query.py", line 82, in __len__
    self._result_cache = list(self.iterator())
  File "/usr/lib/python2.6/site-packages/django/db/models/query.py", line 273, in iterator
    for row in compiler.results_iter():
  File "/usr/lib/python2.6/site-packages/django/db/models/sql/compiler.py", line 680, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/usr/lib/python2.6/site-packages/django/db/models/sql/compiler.py", line 735, in execute_sql
    cursor.execute(sql, params)
  File "/usr/lib/python2.6/site-packages/django/db/backends/postgresql_psycopg2/base.py", line 44, in execute
    return self.cursor.execute(query, args)
DatabaseError: column celery_taskmeta.hidden does not exist
LINE 1: ...meta"."date_done", "celery_taskmeta"."traceback", "celery_ta...

**Comment by michaelschem** [comment]
I don't even seem to have that command.

```
% python manage.py syncdb --migrate --noinput
Unknown command: 'syncdb'. Did you mean absync?
Type 'manage.py help' for usage.
```

Is there a new one now that this is a few years old?

**Comment by auvipy** [comment]
syncdb is not supported, try migrate
