### ISSUE TITLE
Can't start my app!!! djcelery import error

### ISSUE THREAD

**Issue by arkaitzmugica** [celery/django-celery#276]
By mistake I've upgraded djcelery, and now I have this import issue that make our production app to be stopped!!! Please help!!!

import djcelery
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/www/local/lib/python2.7/site-packages/djcelery/**init**.py", line 25, in <module>
    from celery import current_app as celery  # noqa
  File "/home/ubuntu/www/local/lib/python2.7/site-packages/celery/**compat**.py", line 141, in **getattr**
    module = **import**(self._object_origins[name], None, None, [name])
  File "/home/ubuntu/www/local/lib/python2.7/site-packages/celery/_state.py", line 20, in <module>
    from celery.utils.threads import LocalStack
  File "/home/ubuntu/www/local/lib/python2.7/site-packages/celery/utils/__init__.py", line 28, in <module>
    from .functional import noop
  File "/home/ubuntu/www/local/lib/python2.7/site-packages/celery/utils/functional.py", line 19, in <module>
    from kombu.utils.compat import OrderedDict, next
ImportError: cannot import name next

**Comment by namgivu** [comment]
Continued with @karamanolev comment https://github.com/celery/django-celery/issues/276#issuecomment-52148622

To list versions of `kombu`
```
pip install kombu==
```

ref. http://stackoverflow.com/a/26664162/248616
