### ISSUE TITLE
scheduler error

### ISSUE THREAD

**Issue by jerzyk** [celery/django-celery#294]
```
[2013-11-16 21:38:43,043: CRITICAL/MainProcess] beat raised exception <type 'exceptions.TypeError'>: TypeError("can't subtract offset-naive and offset-aware datetimes",)
Traceback (most recent call last):
  File "/home/syg/env/d/lib/python2.7/site-packages/celery/apps/beat.py", line 111, in start_scheduler
    beat.start()
  File "/home/syg/env/d/lib/python2.7/site-packages/celery/beat.py", line 443, in start
    interval = self.scheduler.tick()
  File "/home/syg/env/d/lib/python2.7/site-packages/celery/beat.py", line 212, in tick
    next_time_to_run = self.maybe_due(entry, self.publisher)
  File "/home/syg/env/d/lib/python2.7/site-packages/celery/beat.py", line 190, in maybe_due
    is_due, next_time_to_run = entry.is_due()
  File "/home/syg/env/d/lib/python2.7/site-packages/djcelery/schedulers.py", line 81, in is_due
    return self.schedule.is_due(self.last_run_at)
  File "/home/syg/env/d/lib/python2.7/site-packages/celery/schedules.py", line 117, in is_due
    rem_delta = self.remaining_estimate(last_run_at)
  File "/home/syg/env/d/lib/python2.7/site-packages/celery/schedules.py", line 83, in remaining_estimate
    self.maybe_make_aware(self.now()), self.relative,
  File "/home/syg/env/d/lib/python2.7/site-packages/celery/utils/timeutils.py", line 182, in remaining
    ret = end_date - now
TypeError: can't subtract offset-naive and offset-aware datetimes
```

**Comment by msamoylov** [comment]
That still exists in 2016 with `django-celery==3.1.17`

**Comment by auvipy** [comment]
3.2/master works for that?
