### ISSUE TITLE
`from celery.five import with_metaclass` raises ImportError: No module named five

### ISSUE THREAD

**Issue by ianfp** [celery/django-celery#323]
I've upgraded celery and django-celery to 3.1.10:

```
celery==3.1.10
django-celery==3.1.10
```

I'm using django-celery ([even though it's not required anymore?](http://celery.readthedocs.org/en/latest/django/first-steps-with-django.html)) because I've registered `TaskMeta` in my admin:

```
from djcelery.models import TaskMeta

class TaskMetaAdmin(admin.ModelAdmin):
    readonly_fields = ('result',)

admin.site.register(TaskMeta, TaskMetaAdmin)
```

But I get the above import error. Here's the stack trace:

```
[127.0.0.1:2222] out: Traceback (most recent call last):
[127.0.0.1:2222] out:   File "/my-project/env/lib/python2.7/site-packages/django/core/management/base.py", line 222, in run_from_argv
[127.0.0.1:2222] out:     self.execute(*args, **options.__dict__)
[127.0.0.1:2222] out:   File "/my-project/env/lib/python2.7/site-packages/django/core/management/base.py", line 250, in execute
[127.0.0.1:2222] out:     translation.activate('en-us')
[127.0.0.1:2222] out:   File "/my-project/env/lib/python2.7/site-packages/django/utils/translation/__init__.py", line 90, in activate
[127.0.0.1:2222] out:     return _trans.activate(language)
[127.0.0.1:2222] out:   File "/my-project/env/lib/python2.7/site-packages/django/utils/translation/trans_real.py", line 183, in activate
[127.0.0.1:2222] out:     _active.value = translation(language)
[127.0.0.1:2222] out:   File "/my-project/env/lib/python2.7/site-packages/django/utils/translation/trans_real.py", line 172, in translation
[127.0.0.1:2222] out:     default_translation = _fetch(settings.LANGUAGE_CODE)
[127.0.0.1:2222] out:   File "/my-project/env/lib/python2.7/site-packages/django/utils/translation/trans_real.py", line 154, in _fetch
[127.0.0.1:2222] out:     app = import_module(appname)
[127.0.0.1:2222] out:   File "/my-project/env/lib/python2.7/site-packages/django/utils/importlib.py", line 35, in import_module
[127.0.0.1:2222] out:     __import__(name)
[127.0.0.1:2222] out:   File "/my-project/my-project/api/__init__.py", line 5, in <module>
[127.0.0.1:2222] out:     from tastypie import resources, api as tapi
[127.0.0.1:2222] out:   File "/my-project/env/lib/python2.7/site-packages/tastypie/resources.py", line 19, in <module>
[127.0.0.1:2222] out:     from tastypie.authentication import Authentication
[127.0.0.1:2222] out:   File "/my-project/env/lib/python2.7/site-packages/tastypie/authentication.py", line 14, in <module>
[127.0.0.1:2222] out:     from tastypie.compat import User, username_field
[127.0.0.1:2222] out:   File "/my-project/env/lib/python2.7/site-packages/tastypie/compat.py", line 14, in <module>
[127.0.0.1:2222] out:     User = get_user_model()
[127.0.0.1:2222] out:   File "/my-project/env/lib/python2.7/site-packages/django/contrib/auth/__init__.py", line 127, in get_user_model
[127.0.0.1:2222] out:     user_model = get_model(app_label, model_name)
[127.0.0.1:2222] out:   File "/my-project/env/lib/python2.7/site-packages/django/db/models/loading.py", line 230, in get_model
[127.0.0.1:2222] out:     self._populate()
[127.0.0.1:2222] out:   File "/my-project/env/lib/python2.7/site-packages/django/db/models/loading.py", line 75, in _populate
[127.0.0.1:2222] out:     self.load_app(app_name)
[127.0.0.1:2222] out:   File "/my-project/env/lib/python2.7/site-packages/django/db/models/loading.py", line 96, in load_app
[127.0.0.1:2222] out:     models = import_module('.models', app_name)
[127.0.0.1:2222] out:   File "/my-project/env/lib/python2.7/site-packages/django/utils/importlib.py", line 35, in import_module
[127.0.0.1:2222] out:     __import__(name)
[127.0.0.1:2222] out:   File "/my-project/env/lib/python2.7/site-packages/djcelery/models.py", line 17, in <module>
[127.0.0.1:2222] out:     from .picklefield import PickledObjectField
[127.0.0.1:2222] out:   File "/my-project/env/lib/python2.7/site-packages/djcelery/picklefield.py", line 20, in <module>
[127.0.0.1:2222] out:     from celery.five import with_metaclass
[127.0.0.1:2222] out: ImportError: No module named five
```

**Comment by kqr** [comment]
@ianfp For future Google people, you should probably specify how the configuration was bad.
