### ISSUE TITLE
Deadlock manage.py

### ISSUE THREAD

**Issue by davidfischer-ch** [celery/django-celery#345]
I upgraded django-celery and now it creates a deadlock, manage.py is running forever. 
Obviously removing djcelery from INSTALLED_APPS fixes the issue.

   ^CTraceback (most recent call last):
      File "./manage.py", line 19, in <module>
        execute_from_command_line(sys.argv)
      File "/var/cloudncode/test/venv/src/django/django/core/management/__init__.py", line 334, in execute_from_command_line
        utility.execute()
      File "/var/cloudncode/test/venv/src/django/django/core/management/__init__.py", line 308, in execute
        django.setup()
      File "/var/cloudncode/test/venv/src/django/django/__init__.py", line 21, in setup
        apps.populate(settings.INSTALLED_APPS)
      File "/var/cloudncode/test/venv/src/django/django/apps/registry.py", line 115, in populate
        app_config.ready()
      File "/var/cloudncode/test/venv/src/django/django/contrib/admin/apps.py", line 22, in ready
        self.module.autodiscover()
      File "/var/cloudncode/test/venv/src/django/django/contrib/admin/__init__.py", line 24, in autodiscover
        autodiscover_modules('admin', register_to=site)
      File "/var/cloudncode/test/venv/src/django/django/utils/module_loading.py", line 73, in autodiscover_modules
        import_module('%s.%s' % (app_config.name, module_to_search))
      File "/var/cloudncode/test/venv/lib/python3.4/importlib/__init__.py", line 109, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 2231, in _gcd_import
      File "<frozen importlib._bootstrap>", line 2214, in _find_and_load
      File "<frozen importlib._bootstrap>", line 2203, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
      File "<frozen importlib._bootstrap>", line 1129, in _exec
      File "<frozen importlib._bootstrap>", line 1448, in exec_module
      File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
      File "/var/cloudncode/test/venv/src/django-celery/djcelery/admin.py", line 296, in <module>
        class PeriodicTaskAdmin(admin.ModelAdmin):
      File "/var/cloudncode/test/venv/src/django-celery/djcelery/admin.py", line 298, in PeriodicTaskAdmin
        form = periodic_task_form()
      File "/var/cloudncode/test/venv/src/django-celery/djcelery/admin.py", line 251, in periodic_task_form
        current_app.loader.import_default_modules()
      File "/var/cloudncode/test/venv/lib/python3.4/site-packages/celery/loaders/base.py", line 116, in import_default_modules
        signals.import_modules.send(sender=self.app)
      File "/var/cloudncode/test/venv/lib/python3.4/site-packages/celery/utils/dispatch/signal.py", line 166, in send
        response = receiver(signal=self, sender=sender, **named)
      File "/var/cloudncode/test/venv/lib/python3.4/site-packages/celery/fixups/django.py", line 69, in on_import_modules
        self.worker_fixup.validate_models()
      File "/var/cloudncode/test/venv/lib/python3.4/site-packages/celery/fixups/django.py", line 154, in validate_models
        django_setup()
      File "/var/cloudncode/test/venv/src/django/django/__init__.py", line 21, in setup
        apps.populate(settings.INSTALLED_APPS)
      File "/var/cloudncode/test/venv/src/django/django/apps/registry.py", line 71, in populate
        with self._lock:
    KeyboardInterrupt

**Comment by davidfischer-ch** [comment]
This deadlock is fixed with.

amqp==1.4.6
anyjson==0.3.3
billiard==3.3.0.19
celery==3.1.17
django-celery==3.1
kombu==3.0.24
