### ISSUE TITLE
Creating a model with a ForeignKey on TaskState.task_id causes task clean up to fail.

### ISSUE THREAD

**Issue by asoc** [celery/django-celery#358]
Maybe there's a better way to do what I need to, but at the moment I have a class that includes a ForeignKey relation to TaskState.task_id as follows:

``` python
task = models.ForeignKey(TaskState, null=True, to_field='task_id', on_delete=models.SET_NULL)
```

Now after a while when the cleanup process run, the Celery process throws this error:

``` python
Traceback (most recent call last):
  File "/Development/virtualenvs/csc/lib/python3.4/site-packages/kombu/async/timer.py", line 171, in apply_entry
    entry()
  File "/Development/virtualenvs/csc/lib/python3.4/site-packages/kombu/async/timer.py", line 64, in __call__
    return self.fun(*self.args, **self.kwargs)
  File "/Development/virtualenvs/csc/lib/python3.4/site-packages/kombu/async/timer.py", line 132, in _reschedules
    return fun(*args, **kwargs)
  File "/Development/virtualenvs/csc/lib/python3.4/site-packages/celery/events/snapshot.py", line 64, in cleanup
    self.on_cleanup()
  File "/Development/virtualenvs/csc/lib/python3.4/site-packages/djcelery/snapshot.py", line 147, in on_cleanup
    self.TaskState.objects.purge()
  File "/Development/virtualenvs/csc/lib/python3.4/site-packages/djcelery/managers.py", line 244, in purge
    (True, ),
  File "/usr/local/Cellar/python3/3.4.2_1/Frameworks/Python.framework/Versions/3.4/lib/python3.4/contextlib.py", line 66, in __exit__
    next(self.gen)
  File "/Development/virtualenvs/csc/lib/python3.4/site-packages/djcelery/db.py", line 57, in commit_on_success
    yield
  File "/Development/virtualenvs/csc/lib/python3.4/site-packages/django/db/transaction.py", line 339, in __exit__
    connection.commit()
  File "/Development/virtualenvs/csc/lib/python3.4/site-packages/django/db/backends/__init__.py", line 176, in commit
    self._commit()
  File "/Development/virtualenvs/csc/lib/python3.4/site-packages/django/db/backends/__init__.py", line 145, in _commit
    return self.connection.commit()
  File "/Development/virtualenvs/csc/lib/python3.4/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/Development/virtualenvs/csc/lib/python3.4/site-packages/django/utils/six.py", line 549, in reraise
    raise value.with_traceback(tb)
  File "/Development/virtualenvs/csc/lib/python3.4/site-packages/django/db/backends/__init__.py", line 145, in _commit
    return self.connection.commit()
django.db.utils.IntegrityError: update or delete on table "djcelery_taskstate" violates foreign key constraint "csc_netw_task_id_572dd46d8e053537_fk_djcelery_taskstate_task_id" on table "..."
DETAIL:  Key (task_id)=(ea85fa08-d4ff-4fa9-af43-af5d11422484) is still referenced from table "...".
```

After investigating, I found some hard-coded SQL statements (bad!) in `djcelery.managers.TaskStateManager`'s `purge` method:

``` python
    def purge(self):
        with commit_on_success():
            meta = self.model._meta
            cursor = self.connection_for_write().cursor()
            cursor.execute(
                'DELETE FROM {0.db_table} WHERE hidden=%s'.format(meta),
                (True, ),
            )
```

If I replaced this code to use the Django managers, the error goes away and things are cleaned up:

``` python
    def purge(self):
        self.model.objects.filter(hidden=True).delete()
```

**Comment by ltsampros** [comment]
Any news/updates on this?
