### ISSUE TITLE
TypeError: can't subtract offset-naive and offset-aware datetimes when USE_TZ = True

### ISSUE THREAD

**Issue by MrChoclate** [celery/django-celery#389]
Hello,

I got an issue with time settings.

```
[2015-07-29 23:20:28,691: ERROR/Beat] Process Beat
Traceback (most recent call last):
  File "/home/choclate/documents/projects/web/platform/env/lib/python3.4/site-packages/billiard/process.py", line 292, in _bootstrap
    self.run()
  File "/home/choclate/documents/projects/web/platform/env/lib/python3.4/site-packages/celery/beat.py", line 530, in run
    self.service.start(embedded_process=True)
  File "/home/choclate/documents/projects/web/platform/env/lib/python3.4/site-packages/celery/beat.py", line 463, in start
    interval = self.scheduler.tick()
  File "/home/choclate/documents/projects/web/platform/env/lib/python3.4/site-packages/celery/beat.py", line 221, in tick
    next_time_to_run = self.maybe_due(entry, self.publisher)
  File "/home/choclate/documents/projects/web/platform/env/lib/python3.4/site-packages/celery/beat.py", line 199, in maybe_due
    is_due, next_time_to_run = entry.is_due()
  File "/home/choclate/documents/projects/web/platform/env/lib/python3.4/site-packages/djcelery/schedulers.py", line 83, in is_due
    return self.schedule.is_due(self.last_run_at)
  File "/home/choclate/documents/projects/web/platform/env/lib/python3.4/site-packages/celery/schedules.py", line 118, in is_due
    rem_delta = self.remaining_estimate(last_run_at)
  File "/home/choclate/documents/projects/web/platform/env/lib/python3.4/site-packages/celery/schedules.py", line 84, in remaining_estimate
    self.maybe_make_aware(self.now()), self.relative,
  File "/home/choclate/documents/projects/web/platform/env/lib/python3.4/site-packages/celery/utils/timeutils.py", line 205, in remaining
    ret = end_date - now
TypeError: can't subtract offset-naive and offset-aware datetimes
```

I got a task in app/tasks.py 
```python
@celery.decorators.periodic_task(run_every=datetime.timedelta(seconds=10))
def save_stuff():
    # Do stuff...
```

When I run 
```
python manage.py celery worker -B
```
with USE_TZ = False in my settings.py, it works (but not with USE_TZ = True)

My time settings:
```python
TIME_ZONE = 'Europe/Paris'
USE_TZ = True
CELERY_ENABLE_UTC = True
CELERY_TIMEZONE = pytz.timezone('Europe/Paris')
```

I use:
celery==3.1.18
django-celery==3.1.16

**Comment by MrChoclate** [comment]
Ok @celery.decorators.periodic_task seems to be deprecated. (Maybe add a warning?)
I use CELERYBEAT_SCHEDULE and all seems to works fine.
