### ISSUE TITLE
DatabaseError: DatabaseWrapper objects created in a thread can only be used in that same thread.

### ISSUE THREAD

**Issue by SeanHayes** [celery/django-celery#402]
Django==1.8.6
celery==3.1.19
django-celery==3.1.17
Postgresql

I keep getting this error, I've tried both eventlet and the default worker type:

    Task mysite.giftcards.tasks.EDeliverTask with id 32b60bb3-a538-4990-b854-775f3c97383e raised exception: ‘DatabaseError("DatabaseWrapper objects created in a thread can only be used in that same thread. The object with alias \'default\’ was created in thread id 139742333142032 and this is thread id 139742187524816.",)'

    Task was called with args: [] kwargs: {'order_pk': 1}.

    The contents of the full traceback was:

    Traceback (most recent call last):

    File "/srv/mysite.co/.venv/local/lib/python2.7/site-packages/celery/app/trace.py", line 253, in trace_task
      I, R, state, retval = on_error(task_request, exc, uuid)
    File "/srv/mysite.co/.venv/local/lib/python2.7/site-packages/celery/app/trace.py", line 201, in on_error
      R = I.handle_error_state(task, eager=eager)
    File "/srv/mysite.co/.venv/local/lib/python2.7/site-packages/celery/app/trace.py", line 85, in handle_error_state
      }[self.state](task, store_errors=store_errors)
    File "/srv/mysite.co/.venv/local/lib/python2.7/site-packages/celery/app/trace.py", line 118, in handle_failure
      req.id, exc, einfo.traceback, request=req,
    File "/srv/mysite.co/.venv/local/lib/python2.7/site-packages/celery/backends/base.py", line 121, in mark_as_failure
      traceback=traceback, request=request)
    File "/srv/mysite.co/.venv/local/lib/python2.7/site-packages/celery/backends/base.py", line 257, in store_result
      request=request, **kwargs)
    File "/srv/mysite.co/.venv/local/lib/python2.7/site-packages/djcelery/backends/database.py", line 29, in _store_result
      traceback=traceback, children=self.current_task_children(request),
    File "/srv/mysite.co/.venv/local/lib/python2.7/site-packages/djcelery/managers.py", line 42, in _inner
      return fun(*args, **kwargs)
    File "/srv/mysite.co/.venv/local/lib/python2.7/site-packages/djcelery/managers.py", line 181, in store_result
      'meta': {'children': children}})
    File "/srv/mysite.co/.venv/local/lib/python2.7/site-packages/djcelery/managers.py", line 87, in update_or_create
      return get_queryset(self).update_or_create(**kwargs)
    File "/srv/mysite.co/.venv/local/lib/python2.7/site-packages/djcelery/managers.py", line 70, in update_or_create
      obj, created = self.get_or_create(**kwargs)
    File "/srv/mysite.co/.venv/local/lib/python2.7/site-packages/django/db/models/query.py", line 405, in get_or_create
      return self.get(**lookup), False
    File "/srv/mysite.co/.venv/local/lib/python2.7/site-packages/django/db/models/query.py", line 328, in get
      num = len(clone)
    File "/srv/mysite.co/.venv/local/lib/python2.7/site-packages/django/db/models/query.py", line 144, in __len__
      self._fetch_all()
    File "/srv/mysite.co/.venv/local/lib/python2.7/site-packages/django/db/models/query.py", line 965, in _fetch_all
      self._result_cache = list(self.iterator())
    File "/srv/mysite.co/.venv/local/lib/python2.7/site-packages/django/db/models/query.py", line 238, in iterator
      results = compiler.execute_sql()
    File "/srv/mysite.co/.venv/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 838, in execute_sql
      cursor = self.connection.cursor()
    File "/srv/mysite.co/.venv/local/lib/python2.7/site-packages/django/db/backends/base/base.py", line 160, in cursor
      self.validate_thread_sharing()
    File "/srv/mysite.co/.venv/local/lib/python2.7/site-packages/django/db/backends/base/base.py", line 421, in validate_thread_sharing
      % (self.alias, self._thread_ident, thread.get_ident()))

    DatabaseError: DatabaseWrapper objects created in a thread can only be used in that same thread. The object with alias ‘default’ was created in thread id 139742333142032 and this is thread id 139742187524816.

    — Just to let you know, py-celery at celery@default.queue.

**Comment by gertjanol** [comment]
@SeanHayes Did you find a solution for this problem? We're seeing it.

**Comment by looneychikun** [comment]
I'm especially interested in how to fix this for gevent worker type.  Any solution yet?

**Comment by pappacena** [comment]
+1

**Comment by mx14** [comment]
fix for this issue https://github.com/celery/django-celery/pull/476
