### ISSUE TITLE
Tests fail with Django 1.9

### ISSUE THREAD

**Issue by brianmay** [celery/django-celery#411]
```
I: pybuild base:184: python2.7 setup.py test
running test
............E....EE.....................................E
======================================================================
ERROR: Failure: ImportError (cannot import name get_cache)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/loader.py", line 420, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/lib/python2.7/dist-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib/python2.7/dist-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/«PKGBUILDDIR»/tests/../djcelery/tests/test_backends/test_cache.py", line 16, in <module>
    from djcelery.backends.cache import CacheBackend
  File "/«PKGBUILDDIR»/tests/../djcelery/backends/cache.py", line 8, in <module>
    from django.core.cache import cache, get_cache
ImportError: cannot import name get_cache

======================================================================
ERROR: test_discovery (djcelery.tests.test_discovery.TestDiscovery)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/«PKGBUILDDIR»/tests/../djcelery/tests/test_discovery.py", line 24, in test_discovery
    self.assertDiscovery()
  File "/«PKGBUILDDIR»/tests/../djcelery/tests/test_discovery.py", line 17, in assertDiscovery
    apps = autodiscover()
  File "/«PKGBUILDDIR»/tests/../djcelery/loaders.py", line 184, in autodiscover
    for app in apps.get_app_configs()])
  File "/«PKGBUILDDIR»/tests/../djcelery/loaders.py", line 209, in find_related_module
    return importlib.import_module('{0}.{1}'.format(app, related_name))
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/«PKGBUILDDIR»/tests/someapp/tasks.py", line 3, in <module>
    from django.db.models import get_model
ImportError: cannot import name get_model

======================================================================
ERROR: test_discovery_with_broken (djcelery.tests.test_discovery.TestDiscovery)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/«PKGBUILDDIR»/tests/../djcelery/tests/test_discovery.py", line 44, in test_discovery_with_broken
    autodiscover()
  File "/«PKGBUILDDIR»/tests/../djcelery/loaders.py", line 184, in autodiscover
    for app in apps.get_app_configs()])
  File "/«PKGBUILDDIR»/tests/../djcelery/loaders.py", line 209, in find_related_module
    return importlib.import_module('{0}.{1}'.format(app, related_name))
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/«PKGBUILDDIR»/tests/someapp/tasks.py", line 3, in <module>
    from django.db.models import get_model
ImportError: cannot import name get_model

======================================================================
ERROR: Failure: ImportError (cannot import name get_model)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/loader.py", line 420, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/lib/python2.7/dist-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib/python2.7/dist-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/«PKGBUILDDIR»/tests/someapp/tests.py", line 6, in <module>
    from someapp.tasks import SomeModelTask
  File "/«PKGBUILDDIR»/tests/someapp/tasks.py", line 3, in <module>
    from django.db.models import get_model
ImportError: cannot import name get_model

----------------------------------------------------------------------
Ran 57 tests in 0.354s

FAILED (errors=4)
```

**Comment by brianmay** [comment]
Looks like this project is dead. No response to #342 let alone this bug.

I have created patches for the Debian package just to get the tests working:

http://anonscm.debian.org/cgit/python-modules/packages/django-celery.git/tree/debian/patches/0006-Fix-caching-with-Django-1.9.patch
http://anonscm.debian.org/cgit/python-modules/packages/django-celery.git/tree/debian/patches/0007-Fix-get_model-with-Django-1.9.patch

All the patches in the Debian packaging are here:

http://anonscm.debian.org/cgit/python-modules/packages/django-celery.git/tree/debian/patches

**Comment by gnhuy91** [comment]
thanks @brianmay, a silly question, how can I apply the patches?

**Comment by bharadwaj6** [comment]
@gnhuy91 Not sure what you're asking... you can use git to apply patches. Grab the patch files that have been linked and `git apply` the patch file on the repo. Doing a dry run before patching is considered safe. have a read through these  https://git-scm.com/docs/git-apply https://ariejan.net/2009/10/26/how-to-create-and-apply-a-patch-with-git/

**Comment by gnhuy91** [comment]
thanks, I haven't been through this so I didn't know where to start.

**Comment by azmeuk** [comment]
It would be great to have this fixed soon. Django 1.9 is out from december (more than six months now) and projects relying on django-celery still cannot update. Thanks.

**Comment by jsmedmar** [comment]
has this been released to pypi?

**Comment by brianmay** [comment]
Django 1.10 is now out...

**Comment by b3h3rkz** [comment]
Facing the same problem. Maybe I have to ditch 1.9  for 1.8 until this is resolved.

**Comment by auvipy** [comment]
could you guys try the master branch? will release a new version on pypi hopefully by this weekend

**Comment by d3cline** [comment]
Still broken on pypi I received this bug tonight after a pip3 install, Do you mean the master branch of celery itself or celery-django?

**Comment by auvipy** [comment]
install from github master branch in the mean time.
