### ISSUE TITLE
AttributeError: 'PeriodicTask' object has no attribute '_default_manager'

### ISSUE THREAD

**Issue by fxdgear** [celery/django-celery#433]
Traceback from logs:
```
scheduler_1      | [2016-06-29 21:07:58,164: CRITICAL/MainProcess] beat raised exception <class 'AttributeError'>: AttributeError("'PeriodicTask' object has no attribute '_default_manager'",)
scheduler_1      | Traceback (most recent call last):
scheduler_1      |   File "/usr/lib/python3.5/site-packages/celery/apps/beat.py", line 112, in start_scheduler
scheduler_1      |     beat.start()
scheduler_1      |   File "/usr/lib/python3.5/site-packages/celery/beat.py", line 486, in start
scheduler_1      |     self.scheduler._do_sync()
scheduler_1      |   File "/usr/lib/python3.5/site-packages/celery/beat.py", line 276, in _do_sync
scheduler_1      |     self.sync()
scheduler_1      |   File "/usr/lib/python3.5/site-packages/djcelery/schedulers.py", line 211, in sync
scheduler_1      |     self.schedule[name].save()
scheduler_1      |   File "/usr/lib/python3.5/site-packages/djcelery/schedulers.py", line 98, in save
scheduler_1      |     obj = self.model._default_manager.get(pk=self.model.pk)
```

Running Python3, Django 1.10 pre

The self.model is missing the function `_default_manager`. I'm not sure if this is something that was changed in Django 1.10. 

Doing a bit of poking around I did find that if I changed 

```python
Model = type(self.model)
obj = Model._default_manager.get(pk=self.model.pk)
```
the save function worked as expected. 

edit: see https://code.djangoproject.com/ticket/26652

**Comment by auvipy** [comment]
django 1.10 support hasn't been added yet

**Comment by fxdgear** [comment]
@auvipy 

Is there an ETA on when? 

Would you accept my code suggestion as a patch to be 1.10 ready?

**Comment by fxdgear** [comment]
I can see there is already a PR in place: https://github.com/celery/django-celery/pull/432

**Comment by auvipy** [comment]
merged
