### ISSUE TITLE
./manage.py celeryd failed with django 1.10

### ISSUE THREAD

**Issue by yjmade** [celery/django-celery#462]
I have django-celery master installed with rev 838f59a367de746d27739c50675ddda8de9d6e0a
I start the django-celery by ```./manage.py celeyd```, raise error
```
Traceback (most recent call last):
  File "./manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/yjmade/Envs/pbweb1.10/lib/python2.7/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/Users/yjmade/Envs/pbweb1.10/lib/python2.7/site-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/yjmade/Envs/pbweb1.10/lib/python2.7/site-packages/djcelery/management/base.py", line 101, in run_from_argv
    return super(CeleryCommand, self).run_from_argv(argv)
  File "/Users/yjmade/Envs/pbweb1.10/lib/python2.7/site-packages/django/core/management/base.py", line 305, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/yjmade/Envs/pbweb1.10/lib/python2.7/site-packages/djcelery/management/base.py", line 94, in execute
    super(CeleryCommand, self).execute(*args, **options)
  File "/Users/yjmade/Envs/pbweb1.10/lib/python2.7/site-packages/django/core/management/base.py", line 356, in execute
    output = self.handle(*args, **options)
  File "/Users/yjmade/Envs/pbweb1.10/lib/python2.7/site-packages/djcelery/management/commands/celeryd.py", line 25, in handle
    worker.run(**options)
  File "/Users/yjmade/Envs/pbweb1.10/lib/python2.7/site-packages/celery/bin/worker.py", line 199, in run
    hostname = self.host_format(default_nodename(hostname))
  File "/Users/yjmade/Envs/pbweb1.10/lib/python2.7/site-packages/celery/utils/__init__.py", line 353, in default_nodename
    name, host = nodesplit(hostname or '')
  File "/Users/yjmade/Envs/pbweb1.10/lib/python2.7/site-packages/celery/utils/__init__.py", line 346, in nodesplit
    parts = nodename.split(NODENAME_SEP, 1)
AttributeError: 'tuple' object has no attribute 'split'
```
the nodename here is ('NO', 'DEFAULT')

then if I start with ```python ./manage.py celeryd -n public.%h```, same error raised, but the nodename here is ['public.%h'].

What strange is ```python ./manage.py celeryd_detach --pidfile=./worker.pid -n public.%h``` runs.

Same code runs perfectly with ```django-celery==3.1.17``` and django 1.9

**Comment by ckarrie** [comment]
+1 same here

**Comment by hohenstaufen** [comment]
Same error here

**Comment by Stranger6667** [comment]
Options list, passed to `handle` method of `celeryd` command:

```
{
    'verbosity': 1,
    'beat': ('NO', 'DEFAULT'),
    'no_color': False,
    'pidfile': None,
    'without_gossip': False,
    'working_directory': None,
    'pythonpath': None,
    'exclude_queues': [],
    'state_db': None,
    'purge': False,
    'task_time_limit': None,
    'pool_cls': 'prefork',
    'scheduler_cls': ('NO', 'DEFAULT'),
    'detach': ('NO', 'DEFAULT'),
    'logfile': None,
    'include': [],
    'without_mingle': False,
    'autoscale': ('NO', 'DEFAULT'),
    'optimization': ('NO', 'DEFAULT'),
    'traceback': False,
    'heartbeat_interval': ('NO', 'DEFAULT'),
    'concurrency': 0,
    'send_events': False,
    'schedule_filename': 'celerybeat-schedule',
    'broker': None,
    'hostname': ('NO', 'DEFAULT'),
    'queues': [],
    'task_soft_time_limit': None,
    'executable': None,
    'settings': None,
    'quiet': ('NO', 'DEFAULT'),
    'max_tasks_per_child': None,
    'no_execv': False,
    'gid': None,
    'umask': None,
    'loglevel': 'WARN',
    'without_heartbeat': False,
    'uid': None,
    'autoreload': ('NO', 'DEFAULT')
}
```

It seems like `('NO', 'DEFAULT')` is used everywhere

**Comment by Stranger6667** [comment]
Please, check the latest repository version. It should work (I already tested it at work)

**Comment by yjmade** [comment]
@Stranger6667 @auvipy 
I test with the most recent rev , but it still get problem
```bash
python ./manage.py celeryd -B -l info -n public.%h
Traceback (most recent call last):
  File "./manage.py", line 9, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/yjmade/Envs/pbweb1.10/lib/python2.7/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/Users/yjmade/Envs/pbweb1.10/lib/python2.7/site-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/yjmade/Envs/pbweb1.10/lib/python2.7/site-packages/djcelery/management/base.py", line 103, in run_from_argv
    return super(CeleryCommand, self).run_from_argv(argv)
  File "/Users/yjmade/Envs/pbweb1.10/lib/python2.7/site-packages/django/core/management/base.py", line 305, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/yjmade/Envs/pbweb1.10/lib/python2.7/site-packages/djcelery/management/base.py", line 96, in execute
    super(CeleryCommand, self).execute(*args, **options)
  File "/Users/yjmade/Envs/pbweb1.10/lib/python2.7/site-packages/django/core/management/base.py", line 356, in execute
    output = self.handle(*args, **options)
  File "/Users/yjmade/Envs/pbweb1.10/lib/python2.7/site-packages/djcelery/management/commands/celeryd.py", line 25, in handle
    worker.run(**options)
  File "/Users/yjmade/Envs/pbweb1.10/lib/python2.7/site-packages/celery/bin/worker.py", line 199, in run
    hostname = self.host_format(default_nodename(hostname))
  File "/Users/yjmade/Envs/pbweb1.10/lib/python2.7/site-packages/celery/utils/__init__.py", line 353, in default_nodename
    name, host = nodesplit(hostname or '')
  File "/Users/yjmade/Envs/pbweb1.10/lib/python2.7/site-packages/celery/utils/__init__.py", line 346, in nodesplit
    parts = nodename.split(NODENAME_SEP, 1)
AttributeError: 'list' object has no attribute 'split
```

the variable nodename is ```['public.%h']```

after I remove the -n parameter to 
```bash
python ./manage.py celeryd -B -l info 
Traceback (most recent call last):
  File "./manage.py", line 9, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/yjmade/Envs/pbweb1.10/lib/python2.7/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/Users/yjmade/Envs/pbweb1.10/lib/python2.7/site-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/yjmade/Envs/pbweb1.10/lib/python2.7/site-packages/djcelery/management/base.py", line 103, in run_from_argv
    return super(CeleryCommand, self).run_from_argv(argv)
  File "/Users/yjmade/Envs/pbweb1.10/lib/python2.7/site-packages/django/core/management/base.py", line 305, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/yjmade/Envs/pbweb1.10/lib/python2.7/site-packages/djcelery/management/base.py", line 96, in execute
    super(CeleryCommand, self).execute(*args, **options)
  File "/Users/yjmade/Envs/pbweb1.10/lib/python2.7/site-packages/django/core/management/base.py", line 356, in execute
    output = self.handle(*args, **options)
  File "/Users/yjmade/Envs/pbweb1.10/lib/python2.7/site-packages/djcelery/management/commands/celeryd.py", line 25, in handle
    worker.run(**options)
  File "/Users/yjmade/Envs/pbweb1.10/lib/python2.7/site-packages/celery/bin/worker.py", line 202, in run
    loglevel = mlevel(loglevel)
  File "/Users/yjmade/Envs/pbweb1.10/lib/python2.7/site-packages/celery/utils/log.py", line 119, in mlevel
    return LOG_LEVELS[level.upper()]
AttributeError: 'list' object has no attribute 'upper'
```

the varable here is ```["info"]```

after I remove all the parameters, it works
