### ISSUE TITLE
Celerycam doesn't work with Django 1.10 when error log level is set

### ISSUE THREAD

**Issue by fed239** [celery/django-celery#471]
```
(env)$ python manage.py celerycam -lINFO
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "env/lib/python2.7/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "env/lib/python2.7/site-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "env/lib/python2.7/site-packages/djcelery/management/base.py", line 103, in run_from_argv
    return super(CeleryCommand, self).run_from_argv(argv)
  File "env/lib/python2.7/site-packages/django/core/management/base.py", line 294, in run_from_argv
    self.execute(*args, **cmd_options)
  File "env/lib/python2.7/site-packages/djcelery/management/base.py", line 96, in execute
    super(CeleryCommand, self).execute(*args, **options)
  File "env/lib/python2.7/site-packages/django/core/management/base.py", line 345, in execute
    output = self.handle(*args, **options)
  File "env/lib/python2.7/site-packages/djcelery/management/commands/celerycam.py", line 26, in handle
    ev.run(*args, **options)
  File "env/lib/python2.7/site-packages/celery/bin/events.py", line 86, in run
    detach=detach)
  File "env/lib/python2.7/site-packages/celery/bin/events.py", line 113, in run_evcam
    return cam()
  File "env/lib/python2.7/site-packages/celery/events/snapshot.py", line 97, in evcam
    app.log.setup_logging_subsystem(loglevel, logfile)
  File "env/lib/python2.7/site-packages/celery/app/log.py", line 97, in setup_logging_subsystem
    loglevel = mlevel(loglevel or self.loglevel)
  File "env/lib/python2.7/site-packages/celery/utils/log.py", line 119, in mlevel
    return LOG_LEVELS[level.upper()]
AttributeError: 'list' object has no attribute 'upper'
```

**Comment by vytisb** [comment]
This looks like the same problem as #467.
