### ISSUE TITLE
Require celery<4 in setup.py

### ISSUE THREAD

**Issue by adamcharnock** [celery/django-celery#475]
It sounds like django-celery doesn't support celery 4.0 yet:

https://github.com/celery/celery/issues/3303

Therefore, can the setup.py file be updated to reflect this? My projects CI builds started failing due to this (easily fixed by specifying `celery>=3.1,<4` in my project's setup.py, but still would be nice to fix)

**Comment by auvipy** [comment]
yes because there is new too packages

**Comment by Ulan9304** [comment]
can you help with this please???
Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x03F88660>
Traceback (most recent call last):
  File "C:\Users\Admin\myvenv\lib\site-packages\django\utils\autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "C:\Users\Admin\myvenv\lib\site-packages\django\core\management\commands\runserver.py", line 113, in inner_run
    autoreload.raise_last_exception()
  File "C:\Users\Admin\myvenv\lib\site-packages\django\utils\autoreload.py", line 249, in raise_last_exception
    six.reraise(*_exception)
  File "C:\Users\Admin\myvenv\lib\site-packages\django\utils\six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\Admin\myvenv\lib\site-packages\django\utils\autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "C:\Users\Admin\myvenv\lib\site-packages\django\__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "C:\Users\Admin\myvenv\lib\site-packages\django\apps\registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "C:\Users\Admin\myvenv\lib\site-packages\django\apps\config.py", line 199, in import_models
    self.models_module = import_module(models_module_name)
  File "C:\Program Files (x86)\Python35-32\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "C:\Users\Admin\myvenv\lib\site-packages\djcelery\models.py", line 15, in <module>
    from celery.utils.timeutils import timedelta_seconds
ImportError: No module named 'celery.utils.timeutils'
