### ISSUE TITLE
AttributeError: type object 'BaseCommand' has no attribute 'option_list'

### ISSUE THREAD

**Issue by ccamacho** [celery/django-celery#490]
Django==1.10.2

2016-10-27T16:45:17.152175+00:00 heroku[worker.1]: Process exited with status 1
2016-10-27T16:45:17.172180+00:00 heroku[worker.1]: State changed from up to crashed
2016-10-27T16:45:17.173150+00:00 heroku[worker.1]: State changed from crashed to starting
2016-10-27T16:45:24.724335+00:00 heroku[worker.1]: Starting process with command `python manage.py celery worker --beat --loglevel=info`
2016-10-27T16:45:25.316572+00:00 heroku[worker.1]: State changed from starting to up
2016-10-27T16:45:28.025239+00:00 app[worker.1]: Traceback (most recent call last):
2016-10-27T16:45:28.025260+00:00 app[worker.1]:   File "manage.py", line 22, in <module>
2016-10-27T16:45:28.025266+00:00 app[worker.1]:     execute_from_command_line(sys.argv)
2016-10-27T16:45:28.025267+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/core/management/**init**.py", line 367, in execute_from_command_line
2016-10-27T16:45:28.025335+00:00 app[worker.1]:     utility.execute()
2016-10-27T16:45:28.025414+00:00 app[worker.1]:     self.fetch_command(subcommand).run_from_argv(self.argv)
2016-10-27T16:45:28.025352+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/core/management/**init**.py", line 359, in execute
2016-10-27T16:45:28.025416+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/core/management/**init**.py", line 208, in fetch_command
2016-10-27T16:45:28.025462+00:00 app[worker.1]:     klass = load_command_class(app_name, subcommand)
2016-10-27T16:45:28.025491+00:00 app[worker.1]:     module = import_module('%s.management.commands.%s' % (app_name, name))
2016-10-27T16:45:28.025465+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/core/management/**init**.py", line 40, in load_command_class
2016-10-27T16:45:28.025523+00:00 app[worker.1]:     **import**(name)
2016-10-27T16:45:28.025504+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python2.7/importlib/**init**.py", line 37, in import_module
2016-10-27T16:45:28.025554+00:00 app[worker.1]:     from djcelery.management.base import CeleryCommand
2016-10-27T16:45:28.025558+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/djcelery/management/base.py", line 59, in <module>
2016-10-27T16:45:28.025536+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/djcelery/management/commands/celery.py", line 6, in <module>
2016-10-27T16:45:28.025597+00:00 app[worker.1]:     class CeleryCommand(BaseCommand):
2016-10-27T16:45:28.025599+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/djcelery/management/base.py", line 60, in CeleryCommand
2016-10-27T16:45:28.025615+00:00 app[worker.1]:     options = BaseCommand.option_list
2016-10-27T16:45:28.025631+00:00 app[worker.1]: AttributeError: type object 'BaseCommand' has no attribute 'option_list'
2016-10-27T16:45:28.139351+00:00 heroku[worker.1]: Process exited with status 1
2016-10-27T16:45:28.121140+00:00 heroku[worker.1]: State changed from up to crashed

The problem is that BaseCommand.option_list was deprecated in Django 1.8 and removed in Django 1.10

**Comment by imanhodjaev** [comment]
It was fixed in #458 but not released yet.
