### ISSUE TITLE
ImportError: No module named timeutils

### ISSUE THREAD

**Issue by kxxoling** [celery/django-celery#491]
Got this error when with ``celery==4.0.0rc6`` and ``django-celery==3.1.17``. Full traceback:

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/celery/worker/worker.py", line 204, in start
    self.blueprint.start(self)
  File "/usr/local/lib/python2.7/site-packages/celery/bootsteps.py", line 115, in start
    self.on_start()
  File "/usr/local/lib/python2.7/site-packages/celery/apps/worker.py", line 143, in on_start
    self.emit_banner()
  File "/usr/local/lib/python2.7/site-packages/celery/apps/worker.py", line 158, in emit_banner
    ' \n', self.startup_info(artlines=not use_image))),
  File "/usr/local/lib/python2.7/site-packages/celery/apps/worker.py", line 219, in startup_info
    results=self.app.backend.as_uri(),
  File "/usr/local/lib/python2.7/site-packages/kombu-4.0.0-py2.7.egg/kombu/utils/objects.py", line 44, in __get__
    value = obj.__dict__[self.__name__] = self.__get(obj)
  File "/usr/local/lib/python2.7/site-packages/celery/app/base.py", line 1160, in backend
    return self._get_backend()
  File "/usr/local/lib/python2.7/site-packages/celery/app/base.py", line 878, in _get_backend
    self.loader)
  File "/usr/local/lib/python2.7/site-packages/celery/app/backends.py", line 67, in by_url
    return by_name(backend, loader), url
  File "/usr/local/lib/python2.7/site-packages/celery/app/backends.py", line 47, in by_name
    cls = symbol_by_name(backend, aliases)
  File "/usr/local/lib/python2.7/site-packages/kombu-4.0.0-py2.7.egg/kombu/utils/imports.py", line 56, in symbol_by_name
    module = imp(module_name, package=package, **kwargs)
  File "/usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/local/lib/python2.7/site-packages/djcelery/backends/database.py", line 5, in <module>
    from celery.utils.timeutils import maybe_timedelta
ImportError: No module named timeutils
```

Seems error here was no ``celery.utils.timeutils`` module now, but only ``celery.utils.time``.

**Comment by kxxoling** [comment]
Seems ``djcelery`` does not support ``celery==4.0.0rc6`` yet, closed.

**Comment by spaceone** [comment]
I have the same problem. Should it be supported nowerdays?
