### ISSUE TITLE
ImportError: No module named timeutils

### ISSUE THREAD

**Issue by guirisouza** [celery/django-celery#496]
I trying to follow tutorial install of django-celery. After install i need run migrate to make the necessary tables but appears that error:

(sorry, my english is terrible)

```
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/guilherme/.virtualenvs/martizi-api/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/home/guilherme/.virtualenvs/martizi-api/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 327, in execute
    django.setup()
  File "/home/guilherme/.virtualenvs/martizi-api/local/lib/python2.7/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/guilherme/.virtualenvs/martizi-api/local/lib/python2.7/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/home/guilherme/.virtualenvs/martizi-api/local/lib/python2.7/site-packages/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/guilherme/.virtualenvs/martizi-api/local/lib/python2.7/site-packages/djcelery/models.py", line 15, in <module>
    from celery.utils.timeutils import timedelta_seconds
ImportError: No module named timeutils
```

django-celery doesn't works with celery 4.0?

I've read some posts about and this problem looks like because django-celery does not support this version of celery.

If this issue is righ, how i can downgrade celery because by default djang-celery install an latest version of celery(4.0)?

**Comment by yanikkoval** [comment]
`pip install celery==3.1.17`

**Comment by peykar** [comment]
Document(1) says:
"Module celery.utils.timeutils renamed to celery.utils.time." 
So it's better to update the code, instead of installing an older version of celery.

1. http://docs.celeryproject.org/en/latest/whatsnew-4.0.html#changes-to-internal-api

**Comment by yanikkoval** [comment]
@peykar you can send PR

**Comment by sohaibfarooqi** [comment]
Is this issue fixed somewhere? I am still getting this with celery=4.0.2 and django-celery=3.2.1.
