### ISSUE TITLE
django-celery

### ISSUE THREAD

**Issue by Ulan9304** [celery/django-celery#497]
Good people can you please explain where is the mistake?

Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x03F88660>
Traceback (most recent call last):
  File "C:\Users\Admin\myvenv\lib\site-packages\django\utils\autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "C:\Users\Admin\myvenv\lib\site-packages\django\core\management\commands\runserver.py", line 113, in inner_run
    autoreload.raise_last_exception()
  File "C:\Users\Admin\myvenv\lib\site-packages\django\utils\autoreload.py", line 249, in raise_last_exception
    six.reraise(*_exception)
  File "C:\Users\Admin\myvenv\lib\site-packages\django\utils\six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\Admin\myvenv\lib\site-packages\django\utils\autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "C:\Users\Admin\myvenv\lib\site-packages\django\__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "C:\Users\Admin\myvenv\lib\site-packages\django\apps\registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "C:\Users\Admin\myvenv\lib\site-packages\django\apps\config.py", line 199, in import_models
    self.models_module = import_module(models_module_name)
  File "C:\Program Files (x86)\Python35-32\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "C:\Users\Admin\myvenv\lib\site-packages\djcelery\models.py", line 15, in <module>
    from celery.utils.timeutils import timedelta_seconds
ImportError: No module named 'celery.utils.timeutils'

**Comment by yanikkoval** [comment]
its not working with `celery 4.0+`

**Comment by km-pg** [comment]
I don't believe there are plans to make django-celery work with celery 4.

There are two new packages that replace some of the extra features of django celery that will work with celery 4:
django-celery-beat and django-celery-results

They are described here:
http://docs.celeryproject.org/en/latest/django/first-steps-with-django.html

**Comment by imanhodjaev** [comment]
I just dropped `django-celery` from my current Django project based on the official guides and it works it took some time change configuration name.

So here is the end result

- Create a file called `celery_app.py` with the following contents

```python
# -*- coding: utf-8 -*-
from __future__ import absolute_import

import os

from celery import Celery
from django.conf import settings  # noqa


app = Celery('MyApp')

app.config_from_object('celeryconfig')
app.autodiscover_tasks(settings.INSTALLED_APPS)
```

- Create a file called `celeryconfig.py` and move you configurations, also update them to support the latest changes

- In your Django applications `root_folder/__init__.py` add the following code (it will be at the same module level as the file `celery_app.py`, though you can put it anywhere and just import)

```python
from __future__ import absolute_import, unicode_literals

# This will make sure the app is always imported when
# Django starts so that shared_task will use this app.
from .celery_app import app

__all__ = ['app']
```
