### ISSUE TITLE
MultipleObjectsReturned: get() returned more than one WorkerState

### ISSUE THREAD

**Issue by psychok7** [celery/django-celery#508]
I started getting the following error, not sure why... any ideas on how to fix it?

i am using:
```
celery==3.1.18
django-celery==3.1.16
```

 ```python
[2017-02-08 12:49:47,389: ERROR/MainProcess] Error in timer: MultipleObjectsReturned('get() returned more than one WorkerState -- it returned 2!',)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/kombu/async/timer.py", line 171, in apply_entry
    entry()
  File "/usr/local/lib/python2.7/dist-packages/kombu/async/timer.py", line 64, in __call__
    return self.fun(*self.args, **self.kwargs)
  File "/usr/local/lib/python2.7/dist-packages/kombu/async/timer.py", line 132, in _reschedules
    return fun(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/celery/events/snapshot.py", line 73, in capture
    self.state.freeze_while(self.shutter, clear_after=self.clear_after)
  File "/usr/local/lib/python2.7/dist-packages/celery/events/state.py", line 428, in freeze_while
    return fun(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/celery/events/snapshot.py", line 70, in shutter
    self.on_shutter(self.state)
  File "/usr/local/lib/python2.7/dist-packages/djcelery/snapshot.py", line 127, in on_shutter
    self.handle_worker(worker)
  File "/usr/local/lib/python2.7/dist-packages/djcelery/snapshot.py", line 64, in handle_worker
    defaults={'last_heartbeat': self.get_heartbeat(worker)},
  File "/usr/local/lib/python2.7/dist-packages/djcelery/managers.py", line 87, in update_or_create
    return get_queryset(self).update_or_create(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/djcelery/managers.py", line 70, in update_or_create
    obj, created = self.get_or_create(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 405, in get_or_create
    return self.get(**lookup), False
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 338, in get
    (self.model._meta.object_name, num)
MultipleObjectsReturned: get() returned more than one WorkerState -- it returned 2!
```

**Comment by psychok7** [comment]
My solution was to `WorkerState.objects.all().delete()` and everything started working again
