### ISSUE TITLE
ProgrammingError: relation “djcelery_crontabschedule” already exists

### ISSUE THREAD

**Issue by shubhamxaio** [celery/django-celery#525]
I have made some changes in my model.py, i.e. add **auto_now_add=True** in created_at field and **auto_now=True** in modified_at field, after this I run makemigrations cmd and it was successful:
```
(env) ➜  mdn-core-engine git:(local) ✗ python manage.py makemigrations
Migrations for 'backend':
  0124_auto_20170711_0540.py:
    - Alter field created_at on accountrepresentative
    - Alter field updated_at on accountrepresentative
    - Alter field created_at on availability
    - Alter field updated_at on availability
    - Alter field created_at on campaign
    - Alter field updated_at on campaign


                                 ..and so on
```

After that, I run migrate but it is throwing an exception:

```
(env) ➜  mdn-core-engine git:(local) ✗ python manage.py migrate       
Operations to perform:
  Synchronize unmigrated apps: djcelery_email, django_extensions, messages, rest_framework, corsheaders, staticfiles
  Apply all migrations: auth, mdnbackend, kombu_transport_django, sessions, djcelery, authtoken, contenttypes, admin, csvimport
Synchronizing apps without migrations:
  Creating tables...
    Running deferred SQL...
  Installing custom SQL...
Running migrations:
  Rendering model states... DONE
  Applying csvimport.0003_auto_20170213_0556... OK
  Applying djcelery.0001_initial...Traceback (most recent call last):
  File "/home/mdn/MDN/mdnenv/lib/python3.4/site-packages/django/db/backends/utils.py", line 62, in execute
    return self.cursor.execute(sql)
psycopg2.ProgrammingError: relation "djcelery_crontabschedule" already exists


The above exception was the direct cause of the following exception:


Traceback (most recent call last):
  File "manage.py", line 9, in <module>
    execute_from_command_line(sys.argv)
  File "/home/mdn/MDN/mdnenv/lib/python3.4/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/home/mdn/MDN/mdnenv/lib/python3.4/site-packages/django/core/management/__init__.py", line 330, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/mdn/MDN/mdnenv/lib/python3.4/site-packages/django/core/management/base.py", line 390, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/mdn/MDN/mdnenv/lib/python3.4/site-packages/django/core/management/base.py", line 441, in execute
    output = self.handle(*args, **options)
  File "/home/mdn/MDN/mdnenv/lib/python3.4/site-packages/django/core/management/commands/migrate.py", line 221, in handle
    executor.migrate(targets, plan, fake=fake, fake_initial=fake_initial)
  File "/home/mdn/MDN/mdnenv/lib/python3.4/site-packages/django/db/migrations/executor.py", line 110, in migrate
    self.apply_migration(states[migration], migration, fake=fake, fake_initial=fake_initial)
  File "/home/mdn/MDN/mdnenv/lib/python3.4/site-packages/django/db/migrations/executor.py", line 147, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/home/mdn/MDN/mdnenv/lib/python3.4/site-packages/django/db/migrations/migration.py", line 115, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/home/mdn/MDN/mdnenv/lib/python3.4/site-packages/django/db/migrations/operations/models.py", line 59, in database_forwards
    schema_editor.create_model(model)
  File "/home/mdn/MDN/mdnenv/lib/python3.4/site-packages/django/db/backends/base/schema.py", line 282, in create_model
    self.execute(sql, params or None)
  File "/home/mdn/MDN/mdnenv/lib/python3.4/site-packages/django/db/backends/base/schema.py", line 107, in execute
    cursor.execute(sql, params)
  File "/home/mdn/MDN/mdnenv/lib/python3.4/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/home/mdn/MDN/mdnenv/lib/python3.4/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/mdn/MDN/mdnenv/lib/python3.4/site-packages/django/db/utils.py", line 97, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/mdn/MDN/mdnenv/lib/python3.4/site-packages/django/utils/six.py", line 658, in reraise
    raise value.with_traceback(tb)
  File "/home/mdn/MDN/mdnenv/lib/python3.4/site-packages/django/db/backends/utils.py", line 62, in execute
    return self.cursor.execute(sql)
django.db.utils.ProgrammingError: relation "djcelery_crontabschedule" already exists
```

I am also using **PostgreSQL** as my DB.

**Comment by auvipy** [comment]
it's problem in your migrations not a bug in django celery
