### ISSUE TITLE
ImportError: No module named celery

### ISSUE THREAD

**Issue by leesw98** [celery/django-celery#538]
I get the following error when running `celery -A reboot worker -l info`:

```
Traceback (most recent call last):
  File "/Users/leesw/GitHub/djangoenv/bin/celery", line 11, in <module>
    sys.exit(main())
  File "/Users/leesw/GitHub/djangoenv/lib/python2.7/site-packages/celery/__main__.py", line 30, in main
    main()
  File "/Users/leesw/GitHub/djangoenv/lib/python2.7/site-packages/celery/bin/celery.py", line 81, in main
    cmd.execute_from_commandline(argv)
  File "/Users/leesw/GitHub/djangoenv/lib/python2.7/site-packages/celery/bin/celery.py", line 793, in execute_from_commandline
    super(CeleryCommand, self).execute_from_commandline(argv)))
  File "/Users/leesw/GitHub/djangoenv/lib/python2.7/site-packages/celery/bin/base.py", line 309, in execute_from_commandline
    argv = self.setup_app_from_commandline(argv)
  File "/Users/leesw/GitHub/djangoenv/lib/python2.7/site-packages/celery/bin/base.py", line 469, in setup_app_from_commandline
    self.app = self.find_app(app)
  File "/Users/leesw/GitHub/djangoenv/lib/python2.7/site-packages/celery/bin/base.py", line 489, in find_app
    return find_app(app, symbol_by_name=self.symbol_by_name)
  File "/Users/leesw/GitHub/djangoenv/lib/python2.7/site-packages/celery/app/utils.py", line 254, in find_app
    symbol_by_name=symbol_by_name, imp=imp,
  File "/Users/leesw/GitHub/djangoenv/lib/python2.7/site-packages/celery/app/utils.py", line 238, in find_app
    sym = imp(app)
  File "/Users/leesw/GitHub/djangoenv/lib/python2.7/site-packages/celery/utils/imports.py", line 101, in import_from_cwd
    return imp(module, package=package)
  File "/usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named celery
```

Here is my pip freeze:

```
amqp==1.4.9
anyjson==0.3.3
appdirs==1.4.1
autopep8==1.3.3
backports-abc==0.5
billiard==3.3.0.23
**celery==3.1.25**
certifi==2017.11.5
click==6.7
colorama==0.3.9
coverage==4.4.1
dj-database-url==0.4.2
Django==1.11.6
django-bootstrap3==9.0.0
**django-celery==3.2.2**
django-extensions==1.8.1
django-mathfilters==0.4.0
django-ztask==0.1.5
Flask==0.12.2
Flask-SQLAlchemy==2.3.2
gunicorn==19.7.1
html5lib==1.0b8
itsdangerous==0.24
Jinja2==2.10
kombu==3.0.37
librabbitmq==1.6.1
MarkupSafe==1.0
mysqlclient==1.3.4
numpy==1.13.3
olefile==0.44
packaging==16.8
Pillow==4.3.0
py==1.5.2
pycodestyle==2.3.1
PyMySQL==0.7.11
pyparsing==2.1.10
PyPDF2==1.26.0
pytest==3.2.5
pytest-django==3.1.2
pytz==2017.2
pyzmq==16.0.3
redis==2.10.6
reportlab==3.4.0
scikit-learn==0.19.0
scipy==1.0.0
singledispatch==3.4.0.3
six==1.11.0
sklearn==0.0
South==1.0.2
SQLAlchemy==1.1.15
tornado==4.5.2
vine==1.1.4
virtualenv==15.1.0
webencodings==0.5.1
Werkzeug==0.12.2
whitenoise==3.3.1
xhtml2pdf==0.0.6
```

Any help would be appreciated.

**Comment by thedrow** [comment]
I really don't think this is a problem with Celery. Try reinstalling.
If that doesn't help, ask on StackOverflow.
