### ISSUE TITLE
) optparse.OptionConflictError: option -C/--no-color: conflicting option string(s): --no-color

### ISSUE THREAD

**Issue by anushajp** [celery/django-celery#539]
I used django==1.7 for my project. And now I upgraded my django version to 1.8. I am getting an error while running the following command.

`python manage.py celerycam`

Output:
`Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/dist-packages/djcelery/management/base.py", line 77, in run_from_argv
    return super(CeleryCommand, self).run_from_argv(argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 382, in run_from_argv
    parser = self.create_parser(argv[0], argv[1])
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 331, in create_parser
    parser.add_option(opt)
  File "/usr/lib/python2.7/optparse.py", line 1021, in add_option
    self._check_conflict(option)
  File "/usr/lib/python2.7/optparse.py", line 996, in _check_conflict
    option)
optparse.OptionConflictError: option -C/--no-color: conflicting option string(s): --no-color
`

I am using, 
django-celery==3.1.10
celery==3.1.13

How can I resolve this?

**Comment by auvipy** [comment]
upgrade the django celery to latest version 3.2.2
