### ISSUE TITLE
TypeError: can only concatenate tuple (not "NoneType") to tuple

### ISSUE THREAD

**Issue by jianghaibo12138** [celery/django-celery#560]
Traceback (most recent call last):
  File "/Users/jianghaibo/Python/resource-ret-backend/manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/jianghaibo/.local/share/virtualenvs/resource-ret-backend-HZTWbhOI/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/Users/jianghaibo/.local/share/virtualenvs/resource-ret-backend-HZTWbhOI/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/jianghaibo/.local/share/virtualenvs/resource-ret-backend-HZTWbhOI/lib/python3.6/site-packages/django/core/management/__init__.py", line 224, in fetch_command
    klass = load_command_class(app_name, subcommand)
  File "/Users/jianghaibo/.local/share/virtualenvs/resource-ret-backend-HZTWbhOI/lib/python3.6/site-packages/django/core/management/__init__.py", line 36, in load_command_class
    module = import_module('%s.management.commands.%s' % (app_name, name))
  File "/Users/jianghaibo/.local/share/virtualenvs/resource-ret-backend-HZTWbhOI/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/jianghaibo/.local/share/virtualenvs/resource-ret-backend-HZTWbhOI/lib/python3.6/site-packages/djcelery/management/commands/celery.py", line 11, in <module>
    class Command(CeleryCommand):
  File "/Users/jianghaibo/.local/share/virtualenvs/resource-ret-backend-HZTWbhOI/lib/python3.6/site-packages/djcelery/management/commands/celery.py", line 15, in Command
    base.get_options() +
TypeError: can only concatenate tuple (not "NoneType") to tuple

Process finished with exit code 1

I got an error when i want to start celery by python manage.py celery -l info in django.

**Comment by maxmalysh** [comment]
This is a duplicate of https://github.com/celery/django-celery/issues/573.

Currently, the latest version in PyPi is 3.3.0 and it's broken. It won't even start. @auvipy has fixed the issue, but didn't upload the fixed version yet.

@auvipy could you upload the latest version from master to PyPi, please? Many thanks
