### ISSUE TITLE
TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by leafcoder** [celery/django-celery#585]
Traceback (most recent call last):
  File "./manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/home/ubuntu/.virtualenvs/demo_for_djcelery/lib/python3.5/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/home/ubuntu/.virtualenvs/demo_for_djcelery/lib/python3.5/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/ubuntu/.virtualenvs/demo_for_djcelery/lib/python3.5/site-packages/django/core/management/__init__.py", line 224, in fetch_command
    klass = load_command_class(app_name, subcommand)
  File "/home/ubuntu/.virtualenvs/demo_for_djcelery/lib/python3.5/site-packages/django/core/management/__init__.py", line 36, in load_command_class
    module = import_module('%s.management.commands.%s' % (app_name, name))
  File "/home/ubuntu/.virtualenvs/demo_for_djcelery/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 985, in _gcd_import
  File "<frozen importlib._bootstrap>", line 968, in _find_and_load
  File "<frozen importlib._bootstrap>", line 957, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 697, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/ubuntu/.virtualenvs/demo_for_djcelery/lib/python3.5/site-packages/djcelery/management/commands/celery.py", line 11, in <module>
    class Command(CeleryCommand):
  File "/home/ubuntu/.virtualenvs/demo_for_djcelery/lib/python3.5/site-packages/djcelery/management/commands/celery.py", line 16, in Command
    tuple(base.get_options()) +
TypeError: 'NoneType' object is not iterable

===================================================================
Hello there, I got an error when I run command `./manage.py celery worker -l info -B` in django.

Here's the environment:

python: v3.5.5
celery: v4.3.0
djcelery: v3.3.1
redis: v3.3.11

**Comment by chhatrapal-digiqt** [comment]
how did you solve it?

i have got same problem.

**Comment by leafcoder** [comment]
Yes, it has been fixed before. 

You can see the commit here. https://github.com/celery/django-celery/commit/95c3953321cb25f5e75464d26e03832d3bb56d79
