### ISSUE TITLE
Celery beat not working after upgrading to django 3.0.5

### ISSUE THREAD

**Issue by shivamzxzx** [celery/django-celery#597]
error traceback - 

[2020-05-01 07:37:48,332: WARNING/MainProcess] Traceback (most recent call last):
[2020-05-01 07:37:48,333: WARNING/MainProcess] File "/home/shivam/tmq1/venv2/lib/python3.6/site-packages/kombu/utils/objects.py", line 42, in __get__
[2020-05-01 07:37:48,333: WARNING/MainProcess] return obj.__dict__[self.__name__]
[2020-05-01 07:37:48,333: WARNING/MainProcess] KeyError
[2020-05-01 07:37:48,333: WARNING/MainProcess] :
[2020-05-01 07:37:48,333: WARNING/MainProcess] 'scheduler'
[2020-05-01 07:37:48,333: WARNING/MainProcess] During handling of the above exception, another exception occurred:
[2020-05-01 07:37:48,333: WARNING/MainProcess] Traceback (most recent call last):
[2020-05-01 07:37:48,334: WARNING/MainProcess] File "/home/shivam/tmq1/venv2/bin/celery", line 10, in <module>
[2020-05-01 07:37:48,334: WARNING/MainProcess] sys.exit(main())
[2020-05-01 07:37:48,334: WARNING/MainProcess] File "/home/shivam/tmq1/venv2/lib/python3.6/site-packages/celery/__main__.py", line 16, in main
[2020-05-01 07:37:48,334: WARNING/MainProcess] _main()
[2020-05-01 07:37:48,334: WARNING/MainProcess] File "/home/shivam/tmq1/venv2/lib/python3.6/site-packages/celery/bin/celery.py", line 322, in main
[2020-05-01 07:37:48,334: WARNING/MainProcess] cmd.execute_from_commandline(argv)
[2020-05-01 07:37:48,334: WARNING/MainProcess] File "/home/shivam/tmq1/venv2/lib/python3.6/site-packages/celery/bin/celery.py", line 495, in execute_from_commandline
[2020-05-01 07:37:48,335: WARNING/MainProcess] super(CeleryCommand, self).execute_from_commandline(argv)))
[2020-05-01 07:37:48,335: WARNING/MainProcess] File "/home/shivam/tmq1/venv2/lib/python3.6/site-packages/celery/bin/base.py", line 305, in execute_from_commandline
[2020-05-01 07:37:48,335: WARNING/MainProcess] return self.handle_argv(self.prog_name, argv[1:])
[2020-05-01 07:37:48,335: WARNING/MainProcess] File "/home/shivam/tmq1/venv2/lib/python3.6/site-packages/celery/bin/celery.py", line 487, in handle_argv
[2020-05-01 07:37:48,336: WARNING/MainProcess] return self.execute(command, argv)
[2020-05-01 07:37:48,336: WARNING/MainProcess] File "/home/shivam/tmq1/venv2/lib/python3.6/site-packages/celery/bin/celery.py", line 419, in execute
[2020-05-01 07:37:48,336: WARNING/MainProcess] ).run_from_argv(self.prog_name, argv[1:], command=argv[0])
[2020-05-01 07:37:48,336: WARNING/MainProcess] File "/home/shivam/tmq1/venv2/lib/python3.6/site-packages/celery/bin/base.py", line 309, in run_from_argv
[2020-05-01 07:37:48,336: WARNING/MainProcess] sys.argv if argv is None else argv, command)
[2020-05-01 07:37:48,336: WARNING/MainProcess] File "/home/shivam/tmq1/venv2/lib/python3.6/site-packages/celery/bin/base.py", line 393, in handle_argv
[2020-05-01 07:37:48,337: WARNING/MainProcess] return self(*args, **options)
[2020-05-01 07:37:48,337: WARNING/MainProcess] File "/home/shivam/tmq1/venv2/lib/python3.6/site-packages/celery/bin/base.py", line 253, in __call__
[2020-05-01 07:37:48,337: WARNING/MainProcess] ret = self.run(*args, **kwargs)
[2020-05-01 07:37:48,337: WARNING/MainProcess] File "/home/shivam/tmq1/venv2/lib/python3.6/site-packages/celery/bin/beat.py", line 109, in run
[2020-05-01 07:37:48,337: WARNING/MainProcess] return beat().run()
[2020-05-01 07:37:48,337: WARNING/MainProcess] File "/home/shivam/tmq1/venv2/lib/python3.6/site-packages/celery/apps/beat.py", line 81, in run
[2020-05-01 07:37:48,337: WARNING/MainProcess] self.start_scheduler()
[2020-05-01 07:37:48,338: WARNING/MainProcess] File "/home/shivam/tmq1/venv2/lib/python3.6/site-packages/celery/apps/beat.py", line 109, in start_scheduler
[2020-05-01 07:37:48,338: WARNING/MainProcess] service.start()
[2020-05-01 07:37:48,338: WARNING/MainProcess] File "/home/shivam/tmq1/venv2/lib/python3.6/site-packages/celery/beat.py", line 622, in start
[2020-05-01 07:37:48,338: WARNING/MainProcess] humanize_seconds(self.scheduler.max_interval))
[2020-05-01 07:37:48,338: WARNING/MainProcess] File "/home/shivam/tmq1/venv2/lib/python3.6/site-packages/kombu/utils/objects.py", line 44, in __get__
[2020-05-01 07:37:48,338: WARNING/MainProcess] value = obj.__dict__[self.__name__] = self.__get(obj)
[2020-05-01 07:37:48,339: WARNING/MainProcess] File "/home/shivam/tmq1/venv2/lib/python3.6/site-packages/celery/beat.py", line 666, in scheduler
[2020-05-01 07:37:48,339: WARNING/MainProcess] return self.get_scheduler()
[2020-05-01 07:37:48,339: WARNING/MainProcess] File "/home/shivam/tmq1/venv2/lib/python3.6/site-packages/celery/beat.py", line 661, in get_scheduler
[2020-05-01 07:37:48,339: WARNING/MainProcess] lazy=lazy,
[2020-05-01 07:37:48,340: WARNING/MainProcess] File "/home/shivam/tmq1/venv2/lib/python3.6/site-packages/djcelery/schedulers.py", line 161, in __init__
[2020-05-01 07:37:48,340: WARNING/MainProcess] Scheduler.__init__(self, *args, **kwargs)
[2020-05-01 07:37:48,340: WARNING/MainProcess] File "/home/shivam/tmq1/venv2/lib/python3.6/site-packages/celery/beat.py", line 257, in __init__
[2020-05-01 07:37:48,340: WARNING/MainProcess] self.setup_schedule()
[2020-05-01 07:37:48,340: WARNING/MainProcess] File "/home/shivam/tmq1/venv2/lib/python3.6/site-packages/djcelery/schedulers.py", line 169, in setup_schedule
[2020-05-01 07:37:48,341: WARNING/MainProcess] self.install_default_entries(self.schedule)
[2020-05-01 07:37:48,341: WARNING/MainProcess] File "/home/shivam/tmq1/venv2/lib/python3.6/site-packages/djcelery/schedulers.py", line 263, in schedule
[2020-05-01 07:37:48,341: WARNING/MainProcess] self.sync()
[2020-05-01 07:37:48,341: WARNING/MainProcess] File "/home/shivam/tmq1/venv2/lib/python3.6/site-packages/djcelery/schedulers.py", line 217, in sync
[2020-05-01 07:37:48,341: WARNING/MainProcess] with commit_on_success():
[2020-05-01 07:37:48,341: WARNING/MainProcess] File "/usr/lib/python3.6/contextlib.py", line 81, in __enter__
[2020-05-01 07:37:48,341: WARNING/MainProcess] return next(self.gen)
[2020-05-01 07:37:48,341: WARNING/MainProcess] File "/home/shivam/tmq1/venv2/lib/python3.6/site-packages/djcelery/db.py", line 52, in commit_on_success
[2020-05-01 07:37:48,341: WARNING/MainProcess] if connection.features.autocommits_when_autocommit_is_off:
[2020-05-01 07:37:48,341: WARNING/MainProcess] File "/home/shivam/tmq1/venv2/lib/python3.6/site-packages/django/contrib/gis/db/backends/base/features.py", line 99, in __getattr__
[2020-05-01 07:37:48,342: WARNING/MainProcess] raise AttributeError
[2020-05-01 07:37:48,342: WARNING/MainProcess] AttributeError
[2020-05-01 07:37:48,342: INFO/MainProcess] Writing entries (0)...
[2020-05-01 07:37:48,343: WARNING/MainProcess] Traceback (most recent call last):
[2020-05-01 07:37:48,343: WARNING/MainProcess] File "/usr/lib/python3.6/multiprocessing/util.py", line 262, in _run_finalizers
    finalizer()
[2020-05-01 07:37:48,343: WARNING/MainProcess] File "/usr/lib/python3.6/multiprocessing/util.py", line 186, in __call__
    res = self._callback(*self._args, **self._kwargs)
[2020-05-01 07:37:48,343: WARNING/MainProcess] File "/home/shivam/tmq1/venv2/lib/python3.6/site-packages/djcelery/schedulers.py", line 217, in sync
    with commit_on_success():
[2020-05-01 07:37:48,343: WARNING/MainProcess] File "/usr/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
[2020-05-01 07:37:48,343: WARNING/MainProcess] File "/home/shivam/tmq1/venv2/lib/python3.6/site-packages/djcelery/db.py", line 52, in commit_on_success
    if connection.features.autocommits_when_autocommit_is_off:
[2020-05-01 07:37:48,343: WARNING/MainProcess] File "/home/shivam/tmq1/venv2/lib/python3.6/site-packages/django/contrib/gis/db/backends/base/features.py", line 99, in __getattr__
    raise AttributeError
[2020-05-01 07:37:48,343: WARNING/MainProcess] AttributeError
[2020-05-01 07:37:48,343: INFO/MainProcess] Writing entries (0)...
[2020-05-01 07:37:48,343: WARNING/MainProcess] Traceback (most recent call last):
[2020-05-01 07:37:48,343: WARNING/MainProcess] File "/usr/lib/python3.6/multiprocessing/util.py", line 262, in _run_finalizers
    finalizer()
[2020-05-01 07:37:48,344: WARNING/MainProcess] File "/usr/lib/python3.6/multiprocessing/util.py", line 186, in __call__
    res = self._callback(*self._args, **self._kwargs)
[2020-05-01 07:37:48,344: WARNING/MainProcess] File "/home/shivam/tmq1/venv2/lib/python3.6/site-packages/djcelery/schedulers.py", line 217, in sync
    with commit_on_success():
[2020-05-01 07:37:48,344: WARNING/MainProcess] File "/usr/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
[2020-05-01 07:37:48,344: WARNING/MainProcess] File "/home/shivam/tmq1/venv2/lib/python3.6/site-packages/djcelery/db.py", line 52, in commit_on_success
    if connection.features.autocommits_when_autocommit_is_off:
[2020-05-01 07:37:48,344: WARNING/MainProcess] File "/home/shivam/tmq1/venv2/lib/python3.6/site-packages/django/contrib/gis/db/backends/base/features.py", line 99, in __getattr__
    raise AttributeError
[2020-05-01 07:37:48,344: WARNING/MainProcess] AttributeError

**Comment by auvipy** [comment]
The problem is this package only supports the celery 3.x version and older Django versions. the Django versions after 1.11 lts do not support python 2 either. we might end up adding django 2.2+ support to ease the migration from celery 3.x to 4.x/5.x but new django versions won't support python 2.
