### ISSUE TITLE
Unable to migrate djcelery in django 4.0

### ISSUE THREAD

**Issue by niranjanglynk** [celery/django-celery#616]
`python3 manage.py migrate djcelery`

causes this error - 

`ImportError: cannot import name 'ugettext_lazy' from 'django.utils.translation' (/Library/Python/3.8/site-packages/django/utils/translation/__init__.py)`

here's the stack trace - 

```
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    main()
  File "manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/Library/Python/3.8/site-packages/django/core/management/__init__.py", line 425, in execute_from_command_line
    utility.execute()
  File "/Library/Python/3.8/site-packages/django/core/management/__init__.py", line 401, in execute
    django.setup()
  File "/Library/Python/3.8/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Library/Python/3.8/site-packages/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "/Library/Python/3.8/site-packages/django/apps/config.py", line 300, in import_models
    self.models_module = import_module(models_module_name)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Library/Python/3.8/site-packages/djcelery/models.py", line 9, in <module>
    from django.utils.translation import ugettext_lazy as _
ImportError: cannot import name 'ugettext_lazy' from 'django.utils.translation' (/Library/Python/3.8/site-packages/django/utils/translation/__init__.py)
```

Looks like ugettext_lazy is removed in 4.0

**Comment by auvipy** [comment]
its only for celery 3.x and older django versions

**Comment by niranjanglynk** [comment]
> its only for celery 3.x and older django versions

but looks like `pip install django-celery` installs 3.1.26 by default. and installing the latest celery(5.2.6) throws this error - 

`django-celery 3.3.1 requires celery<4.0,>=3.1.15, but you'll have celery 5.2.6 which is incompatible.`

i am using django 4.0

**Comment by auvipy** [comment]
https://github.com/celery/django-celery-beat this and https://github.com/celery/django-celery-results are the suggested alternatives

**Comment by niranjanglynk** [comment]
> https://github.com/celery/django-celery-beat this and https://github.com/celery/django-celery-results are the suggested alternatives

i'm sorry. looks like they are not. they are very different packages to solve different problems compared to djcelery.

**Comment by niranjanglynk** [comment]
why is the issue closed? @auvipy
