### ISSUE TITLE
celery cannot connect to postgresql

### ISSUE THREAD

**Issue by rashideveloperr** [celery/django-celery#626]
```
[2023-07-05 14:33:04,796: INFO/MainProcess] Task marathon.tasks.send_question_to_users[a6329030-7b30-4577-abcf-d3c0554fefbd] received
[2023-07-05 14:33:04,878: WARNING/ForkPoolWorker-8] /home/rashideveloper/.cache/pypoetry/virtualenvs/marathon-avitcenna--IRyX58E-py3.11/lib/python3.11/site-packages/celery/app/trace.py:686: RuntimeWarning: Exception raised outside body: OperationalError('connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory\n\tIs the server running locally and accepting connections on that socket?\n'):
Traceback (most recent call last):
  File "/home/rashideveloper/.cache/pypoetry/virtualenvs/marathon-avitcenna--IRyX58E-py3.11/lib/python3.11/site-packages/django/db/backends/base/base.py", line 289, in ensure_connection
    self.connect()
  File "/home/rashideveloper/.cache/pypoetry/virtualenvs/marathon-avitcenna--IRyX58E-py3.11/lib/python3.11/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/rashideveloper/.cache/pypoetry/virtualenvs/marathon-avitcenna--IRyX58E-py3.11/lib/python3.11/site-packages/django/db/backends/base/base.py", line 270, in connect
    self.connection = self.get_new_connection(conn_params)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rashideveloper/.cache/pypoetry/virtualenvs/marathon-avitcenna--IRyX58E-py3.11/lib/python3.11/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/rashideveloper/.cache/pypoetry/virtualenvs/marathon-avitcenna--IRyX58E-py3.11/lib/python3.11/site-packages/django/db/backends/postgresql/base.py", line 275, in get_new_connection
    connection = self.Database.connect(**conn_params)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rashideveloper/.cache/pypoetry/virtualenvs/marathon-avitcenna--IRyX58E-py3.11/lib/python3.11/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.OperationalError: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
        Is the server running locally and accepting connections on that socket?


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/rashideveloper/.cache/pypoetry/virtualenvs/marathon-avitcenna--IRyX58E-py3.11/lib/python3.11/site-packages/celery/app/trace.py", line 477, in trace_task
    R = retval = fun(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^
  File "/home/rashideveloper/.cache/pypoetry/virtualenvs/marathon-avitcenna--IRyX58E-py3.11/lib/python3.11/site-packages/celery/app/trace.py", line 760, in __protected_call__
    return self.run(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rashideveloper/PycharmProjects/marathon_avitcenna/marathon/tasks.py", line 37, in send_question_to_users
    async_to_sync(send_to_all)(question_id)
  File "/home/rashideveloper/.cache/pypoetry/virtualenvs/marathon-avitcenna--IRyX58E-py3.11/lib/python3.11/site-packages/asgiref/sync.py", line 277, in __call__
    return call_result.result()
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/home/rashideveloper/.cache/pypoetry/virtualenvs/marathon-avitcenna--IRyX58E-py3.11/lib/python3.11/site-packages/asgiref/sync.py", line 353, in main_wrap
    result = await self.awaitable(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rashideveloper/PycharmProjects/marathon_avitcenna/marathon/tasks.py", line 14, in send_to_all
    question = await Question.objects.aget(pk=question_id)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rashideveloper/.cache/pypoetry/virtualenvs/marathon-avitcenna--IRyX58E-py3.11/lib/python3.11/site-packages/django/db/models/query.py", line 649, in aget
    return await sync_to_async(self.get)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rashideveloper/.cache/pypoetry/virtualenvs/marathon-avitcenna--IRyX58E-py3.11/lib/python3.11/site-packages/asgiref/sync.py", line 479, in __call__
    ret: _R = await loop.run_in_executor(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rashideveloper/.cache/pypoetry/virtualenvs/marathon-avitcenna--IRyX58E-py3.11/lib/python3.11/site-packages/asgiref/current_thread_executor.py", line 40, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rashideveloper/.cache/pypoetry/virtualenvs/marathon-avitcenna--IRyX58E-py3.11/lib/python3.11/site-packages/asgiref/sync.py", line 538, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/rashideveloper/.cache/pypoetry/virtualenvs/marathon-avitcenna--IRyX58E-py3.11/lib/python3.11/site-packages/django/db/models/query.py", line 633, in get
    num = len(clone)
          ^^^^^^^^^^
  File "/home/rashideveloper/.cache/pypoetry/virtualenvs/marathon-avitcenna--IRyX58E-py3.11/lib/python3.11/site-packages/django/db/models/query.py", line 380, in __len__
    self._fetch_all()
  File "/home/rashideveloper/.cache/pypoetry/virtualenvs/marathon-avitcenna--IRyX58E-py3.11/lib/python3.11/site-packages/django/db/models/query.py", line 1881, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rashideveloper/.cache/pypoetry/virtualenvs/marathon-avitcenna--IRyX58E-py3.11/lib/python3.11/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "/home/rashideveloper/.cache/pypoetry/virtualenvs/marathon-avitcenna--IRyX58E-py3.11/lib/python3.11/site-packages/django/db/models/sql/compiler.py", line 1560, in execute_sql
    cursor = self.connection.cursor()
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rashideveloper/.cache/pypoetry/virtualenvs/marathon-avitcenna--IRyX58E-py3.11/lib/python3.11/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/rashideveloper/.cache/pypoetry/virtualenvs/marathon-avitcenna--IRyX58E-py3.11/lib/python3.11/site-packages/django/db/backends/base/base.py", line 330, in cursor
    return self._cursor()
           ^^^^^^^^^^^^^^
  File "/home/rashideveloper/.cache/pypoetry/virtualenvs/marathon-avitcenna--IRyX58E-py3.11/lib/python3.11/site-packages/django/db/backends/base/base.py", line 306, in _cursor
    self.ensure_connection()
  File "/home/rashideveloper/.cache/pypoetry/virtualenvs/marathon-avitcenna--IRyX58E-py3.11/lib/python3.11/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/rashideveloper/.cache/pypoetry/virtualenvs/marathon-avitcenna--IRyX58E-py3.11/lib/python3.11/site-packages/django/db/backends/base/base.py", line 288, in ensure_connection
    with self.wrap_database_errors:
  File "/home/rashideveloper/.cache/pypoetry/virtualenvs/marathon-avitcenna--IRyX58E-py3.11/lib/python3.11/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/rashideveloper/.cache/pypoetry/virtualenvs/marathon-avitcenna--IRyX58E-py3.11/lib/python3.11/site-packages/django/db/backends/base/base.py", line 289, in ensure_connection
    self.connect()
  File "/home/rashideveloper/.cache/pypoetry/virtualenvs/marathon-avitcenna--IRyX58E-py3.11/lib/python3.11/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/rashideveloper/.cache/pypoetry/virtualenvs/marathon-avitcenna--IRyX58E-py3.11/lib/python3.11/site-packages/django/db/backends/base/base.py", line 270, in connect
    self.connection = self.get_new_connection(conn_params)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rashideveloper/.cache/pypoetry/virtualenvs/marathon-avitcenna--IRyX58E-py3.11/lib/python3.11/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/rashideveloper/.cache/pypoetry/virtualenvs/marathon-avitcenna--IRyX58E-py3.11/lib/python3.11/site-packages/django/db/backends/postgresql/base.py", line 275, in get_new_connection
    connection = self.Database.connect(**conn_params)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rashideveloper/.cache/pypoetry/virtualenvs/marathon-avitcenna--IRyX58E-py3.11/lib/python3.11/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
        Is the server running locally and accepting connections on that socket?


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rashideveloper/.cache/pypoetry/virtualenvs/marathon-avitcenna--IRyX58E-py3.11/lib/python3.11/site-packages/django/db/backends/base/base.py", line 289, in ensure_connection
    self.connect()
  File "/home/rashideveloper/.cache/pypoetry/virtualenvs/marathon-avitcenna--IRyX58E-py3.11/lib/python3.11/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/rashideveloper/.cache/pypoetry/virtualenvs/marathon-avitcenna--IRyX58E-py3.11/lib/python3.11/site-packages/django/db/backends/base/base.py", line 270, in connect
    self.connection = self.get_new_connection(conn_params)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rashideveloper/.cache/pypoetry/virtualenvs/marathon-avitcenna--IRyX58E-py3.11/lib/python3.11/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/rashideveloper/.cache/pypoetry/virtualenvs/marathon-avitcenna--IRyX58E-py3.11/lib/python3.11/site-packages/django/db/backends/postgresql/base.py", line 275, in get_new_connection
    connection = self.Database.connect(**conn_params)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rashideveloper/.cache/pypoetry/virtualenvs/marathon-avitcenna--IRyX58E-py3.11/lib/python3.11/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.OperationalError: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
        Is the server running locally and accepting connections on that socket?


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/rashideveloper/.cache/pypoetry/virtualenvs/marathon-avitcenna--IRyX58E-py3.11/lib/python3.11/site-packages/celery/app/trace.py", line 494, in trace_task
    I, R, state, retval = on_error(task_request, exc)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rashideveloper/.cache/pypoetry/virtualenvs/marathon-avitcenna--IRyX58E-py3.11/lib/python3.11/site-packages/celery/app/trace.py", line 399, in on_error
    R = I.handle_error_state(
        ^^^^^^^^^^^^^^^^^^^^^
  File "/home/rashideveloper/.cache/pypoetry/virtualenvs/marathon-avitcenna--IRyX58E-py3.11/lib/python3.11/site-packages/celery/app/trace.py", line 178, in handle_error_state
    return {
           ^
  File "/home/rashideveloper/.cache/pypoetry/virtualenvs/marathon-avitcenna--IRyX58E-py3.11/lib/python3.11/site-packages/celery/app/trace.py", line 230, in handle_failure
    task.backend.mark_as_failure(
  File "/home/rashideveloper/.cache/pypoetry/virtualenvs/marathon-avitcenna--IRyX58E-py3.11/lib/python3.11/site-packages/celery/backends/base.py", line 167, in mark_as_failure
    self.store_result(task_id, exc, state,
  File "/home/rashideveloper/.cache/pypoetry/virtualenvs/marathon-avitcenna--IRyX58E-py3.11/lib/python3.11/site-packages/celery/backends/base.py", line 526, in store_result
    self._store_result(task_id, result, state, traceback,
  File "/home/rashideveloper/.cache/pypoetry/virtualenvs/marathon-avitcenna--IRyX58E-py3.11/lib/python3.11/site-packages/django_celery_results/backends/database.py", line 147, in _store_result
    self.TaskModel._default_manager.store_result(**task_props)
  File "/home/rashideveloper/.cache/pypoetry/virtualenvs/marathon-avitcenna--IRyX58E-py3.11/lib/python3.11/site-packages/django_celery_results/managers.py", line 42, in _inner
    return fun(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/rashideveloper/.cache/pypoetry/virtualenvs/marathon-avitcenna--IRyX58E-py3.11/lib/python3.11/site-packages/django_celery_results/managers.py", line 164, in store_result
    obj, created = self.using(using).get_or_create(task_id=task_id,
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rashideveloper/.cache/pypoetry/virtualenvs/marathon-avitcenna--IRyX58E-py3.11/lib/python3.11/site-packages/django/db/models/query.py", line 916, in get_or_create
    return self.get(**kwargs), False
           ^^^^^^^^^^^^^^^^^^
  File "/home/rashideveloper/.cache/pypoetry/virtualenvs/marathon-avitcenna--IRyX58E-py3.11/lib/python3.11/site-packages/django/db/models/query.py", line 633, in get
    num = len(clone)
          ^^^^^^^^^^
  File "/home/rashideveloper/.cache/pypoetry/virtualenvs/marathon-avitcenna--IRyX58E-py3.11/lib/python3.11/site-packages/django/db/models/query.py", line 380, in __len__
    self._fetch_all()
  File "/home/rashideveloper/.cache/pypoetry/virtualenvs/marathon-avitcenna--IRyX58E-py3.11/lib/python3.11/site-packages/django/db/models/query.py", line 1881, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rashideveloper/.cache/pypoetry/virtualenvs/marathon-avitcenna--IRyX58E-py3.11/lib/python3.11/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "/home/rashideveloper/.cache/pypoetry/virtualenvs/marathon-avitcenna--IRyX58E-py3.11/lib/python3.11/site-packages/django/db/models/sql/compiler.py", line 1560, in execute_sql
    cursor = self.connection.cursor()
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rashideveloper/.cache/pypoetry/virtualenvs/marathon-avitcenna--IRyX58E-py3.11/lib/python3.11/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/rashideveloper/.cache/pypoetry/virtualenvs/marathon-avitcenna--IRyX58E-py3.11/lib/python3.11/site-packages/django/db/backends/base/base.py", line 330, in cursor
    return self._cursor()
           ^^^^^^^^^^^^^^
  File "/home/rashideveloper/.cache/pypoetry/virtualenvs/marathon-avitcenna--IRyX58E-py3.11/lib/python3.11/site-packages/django/db/backends/base/base.py", line 306, in _cursor
    self.ensure_connection()
  File "/home/rashideveloper/.cache/pypoetry/virtualenvs/marathon-avitcenna--IRyX58E-py3.11/lib/python3.11/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/rashideveloper/.cache/pypoetry/virtualenvs/marathon-avitcenna--IRyX58E-py3.11/lib/python3.11/site-packages/django/db/backends/base/base.py", line 288, in ensure_connection
    with self.wrap_database_errors:
  File "/home/rashideveloper/.cache/pypoetry/virtualenvs/marathon-avitcenna--IRyX58E-py3.11/lib/python3.11/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/rashideveloper/.cache/pypoetry/virtualenvs/marathon-avitcenna--IRyX58E-py3.11/lib/python3.11/site-packages/django/db/backends/base/base.py", line 289, in ensure_connection
    self.connect()
  File "/home/rashideveloper/.cache/pypoetry/virtualenvs/marathon-avitcenna--IRyX58E-py3.11/lib/python3.11/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/rashideveloper/.cache/pypoetry/virtualenvs/marathon-avitcenna--IRyX58E-py3.11/lib/python3.11/site-packages/django/db/backends/base/base.py", line 270, in connect
    self.connection = self.get_new_connection(conn_params)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rashideveloper/.cache/pypoetry/virtualenvs/marathon-avitcenna--IRyX58E-py3.11/lib/python3.11/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/rashideveloper/.cache/pypoetry/virtualenvs/marathon-avitcenna--IRyX58E-py3.11/lib/python3.11/site-packages/django/db/backends/postgresql/base.py", line 275, in get_new_connection
    connection = self.Database.connect(**conn_params)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rashideveloper/.cache/pypoetry/virtualenvs/marathon-avitcenna--IRyX58E-py3.11/lib/python3.11/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
        Is the server running locally and accepting connections on that socket?


  warn(RuntimeWarning(

[2023-07-05 14:33:04,925: ERROR/MainProcess] Pool callback raised exception: OperationalError('connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory\n\tIs the server running locally and accepting connections on that socket?\n')
Traceback (most recent call last):
  File "/home/rashideveloper/.cache/pypoetry/virtualenvs/marathon-avitcenna--IRyX58E-py3.11/lib/python3.11/site-packages/django/db/backends/base/base.py", line 289, in ensure_connection
    self.connect()
  File "/home/rashideveloper/.cache/pypoetry/virtualenvs/marathon-avitcenna--IRyX58E-py3.11/lib/python3.11/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/rashideveloper/.cache/pypoetry/virtualenvs/marathon-avitcenna--IRyX58E-py3.11/lib/python3.11/site-packages/django/db/backends/base/base.py", line 270, in connect
    self.connection = self.get_new_connection(conn_params)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rashideveloper/.cache/pypoetry/virtualenvs/marathon-avitcenna--IRyX58E-py3.11/lib/python3.11/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/rashideveloper/.cache/pypoetry/virtualenvs/marathon-avitcenna--IRyX58E-py3.11/lib/python3.11/site-packages/django/db/backends/postgresql/base.py", line 275, in get_new_connection
    connection = self.Database.connect(**conn_params)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rashideveloper/.cache/pypoetry/virtualenvs/marathon-avitcenna--IRyX58E-py3.11/lib/python3.11/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.OperationalError: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
        Is the server running locally and accepting connections on that socket?


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/rashideveloper/.cache/pypoetry/virtualenvs/marathon-avitcenna--IRyX58E-py3.11/lib/python3.11/site-packages/billiard/pool.py", line 1793, in safe_apply_callback
    fun(*args, **kwargs)
  File "/home/rashideveloper/.cache/pypoetry/virtualenvs/marathon-avitcenna--IRyX58E-py3.11/lib/python3.11/site-packages/celery/worker/request.py", line 624, in on_failure
    self.task.backend.mark_as_failure(
  File "/home/rashideveloper/.cache/pypoetry/virtualenvs/marathon-avitcenna--IRyX58E-py3.11/lib/python3.11/site-packages/celery/backends/base.py", line 167, in mark_as_failure
    self.store_result(task_id, exc, state,
  File "/home/rashideveloper/.cache/pypoetry/virtualenvs/marathon-avitcenna--IRyX58E-py3.11/lib/python3.11/site-packages/celery/backends/base.py", line 526, in store_result
    self._store_result(task_id, result, state, traceback,
  File "/home/rashideveloper/.cache/pypoetry/virtualenvs/marathon-avitcenna--IRyX58E-py3.11/lib/python3.11/site-packages/django_celery_results/backends/database.py", line 147, in _store_result
    self.TaskModel._default_manager.store_result(**task_props)
  File "/home/rashideveloper/.cache/pypoetry/virtualenvs/marathon-avitcenna--IRyX58E-py3.11/lib/python3.11/site-packages/django_celery_results/managers.py", line 42, in _inner
    return fun(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/rashideveloper/.cache/pypoetry/virtualenvs/marathon-avitcenna--IRyX58E-py3.11/lib/python3.11/site-packages/django_celery_results/managers.py", line 164, in store_result
    obj, created = self.using(using).get_or_create(task_id=task_id,
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rashideveloper/.cache/pypoetry/virtualenvs/marathon-avitcenna--IRyX58E-py3.11/lib/python3.11/site-packages/django/db/models/query.py", line 916, in get_or_create
    return self.get(**kwargs), False
           ^^^^^^^^^^^^^^^^^^
  File "/home/rashideveloper/.cache/pypoetry/virtualenvs/marathon-avitcenna--IRyX58E-py3.11/lib/python3.11/site-packages/django/db/models/query.py", line 633, in get
    num = len(clone)
          ^^^^^^^^^^
  File "/home/rashideveloper/.cache/pypoetry/virtualenvs/marathon-avitcenna--IRyX58E-py3.11/lib/python3.11/site-packages/django/db/models/query.py", line 380, in __len__
    self._fetch_all()
  File "/home/rashideveloper/.cache/pypoetry/virtualenvs/marathon-avitcenna--IRyX58E-py3.11/lib/python3.11/site-packages/django/db/models/query.py", line 1881, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rashideveloper/.cache/pypoetry/virtualenvs/marathon-avitcenna--IRyX58E-py3.11/lib/python3.11/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "/home/rashideveloper/.cache/pypoetry/virtualenvs/marathon-avitcenna--IRyX58E-py3.11/lib/python3.11/site-packages/django/db/models/sql/compiler.py", line 1560, in execute_sql
    cursor = self.connection.cursor()
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rashideveloper/.cache/pypoetry/virtualenvs/marathon-avitcenna--IRyX58E-py3.11/lib/python3.11/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/rashideveloper/.cache/pypoetry/virtualenvs/marathon-avitcenna--IRyX58E-py3.11/lib/python3.11/site-packages/django/db/backends/base/base.py", line 330, in cursor
    return self._cursor()
           ^^^^^^^^^^^^^^
  File "/home/rashideveloper/.cache/pypoetry/virtualenvs/marathon-avitcenna--IRyX58E-py3.11/lib/python3.11/site-packages/django/db/backends/base/base.py", line 306, in _cursor
    self.ensure_connection()
  File "/home/rashideveloper/.cache/pypoetry/virtualenvs/marathon-avitcenna--IRyX58E-py3.11/lib/python3.11/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/rashideveloper/.cache/pypoetry/virtualenvs/marathon-avitcenna--IRyX58E-py3.11/lib/python3.11/site-packages/django/db/backends/base/base.py", line 288, in ensure_connection
    with self.wrap_database_errors:
  File "/home/rashideveloper/.cache/pypoetry/virtualenvs/marathon-avitcenna--IRyX58E-py3.11/lib/python3.11/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/rashideveloper/.cache/pypoetry/virtualenvs/marathon-avitcenna--IRyX58E-py3.11/lib/python3.11/site-packages/django/db/backends/base/base.py", line 289, in ensure_connection
    self.connect()
  File "/home/rashideveloper/.cache/pypoetry/virtualenvs/marathon-avitcenna--IRyX58E-py3.11/lib/python3.11/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/rashideveloper/.cache/pypoetry/virtualenvs/marathon-avitcenna--IRyX58E-py3.11/lib/python3.11/site-packages/django/db/backends/base/base.py", line 270, in connect
    self.connection = self.get_new_connection(conn_params)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rashideveloper/.cache/pypoetry/virtualenvs/marathon-avitcenna--IRyX58E-py3.11/lib/python3.11/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/rashideveloper/.cache/pypoetry/virtualenvs/marathon-avitcenna--IRyX58E-py3.11/lib/python3.11/site-packages/django/db/backends/postgresql/base.py", line 275, in get_new_connection
    connection = self.Database.connect(**conn_params)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rashideveloper/.cache/pypoetry/virtualenvs/marathon-avitcenna--IRyX58E-py3.11/lib/python3.11/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
        Is the server running locally and accepting connections on that socket?



```

what is wrong? 

my postgresql database incide docker

my celery.py
```import os
from celery import Celery

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'root.settings')

background_worker = Celery('root')
background_worker.conf.broker_connection_retry_on_startup = True
background_worker.config_from_object('django.conf:settings', namespace='CELERY')
background_worker.autodiscover_tasks()
```

**Comment by auvipy** [comment]
you are trying to use  a discontinued package.

**Comment by rashideveloperr** [comment]
@auvipy which package discounted?

**Comment by amirhosein-kia-darbandsary** [comment]
### Why is this code (`os.environ.setdefault`) not enough?

This code only specifies the path to the Django settings, but:

1. If the database settings in `settings.py` depend on environment variables (e.g., `DB_NAME`, `DB_USER`, etc.), these variables must be present in the environment where Celery is running.
2. If these variables are not defined in the environment where Celery is running, Celery will not be able to connect to the database.

---

### Final Solution:

1. Ensure that all required environment variables (e.g., `DB_NAME`, `DB_USER`, `DB_PASSWORD`, etc.) are defined in `docker-compose.yml` for the `celery` service.
2. If you are not using Docker, make sure these variables are defined in the environment where Celery is running (e.g., in the operating system or in a `.env` file).
3. If you are using `django-environ` or similar libraries, ensure that the `.env` file is loaded correctly.


### P.s

I've this problem for the celery-beat too so don't forget.
